RECAST_ORCID_APPID: 'ORCID_APPID'
RECAST_ORCID_REDIRECT_URI: 'ORCID_REDIRECT_URI'
RECAST_ORCID_SECRET: 'ORCID_SECRET'
RECAST_ORCID_TOKEN_REDIRECT_URI: 'ORCID_TOKEN_REDIRECT_URI'
RECAST_AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
RECAST_AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
RECAST_AWS_S3_BUCKET_NAME: 'recast'
RECAST_HOSTNAME: 'localhost'
RECAST_REDISURL: 'redis://localhost:6379/0'
RECAST_CELERYAPP: 'recastfrontend.celeryapp'
RECAST_FLASKCONFIG: 'recastfrontend.flaskconfig'
RECAST_DATA_FOLDER: 'data/'
RECAST_DBPATH: 'sqlite:///tmp.db'
RECAST_SSL_CERT: 'server.crt'
RECAST_SSL_KEY: 'server.key'
