from ...tl.tlobject import TLObject


class ChatPhotoEmpty(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    chatPhotoEmpty#37c1011c = ChatPhoto"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x37c1011c
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xac3ec4e5

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(ChatPhotoEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return ChatPhotoEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'chatPhotoEmpty#37c1011c = ChatPhoto'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
