SQS_ACCESS_KEY = 'AKIAI4G62B7HXGRAWYPA'
SQS_SECRET_KEY = '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'
QUEUE_NAME = 'sa-event-bus'
DYN_ACCESS_KEY = 'AKIAIFP6UM64MH2XKYOA'
DYN_SECRET_KEY = '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'
DYN_TABLE_NAME = 'sa-event-bus-lock-test'


GIGYA_USER_KEY = 'APwVKcxsMuP8'
GIGYA_USER_SECRET = 'bKA4qJEznyiLC74Wgy1FrgtdwXYkz1w1'
ERROR_PREFIX = "[ERROR] "
GIGYA_API_KEY = '3_aWOpZXJURMRPH05pBUwusoKBU1E10WxtZFx5zoF3AheB5Sx28aa242B23V1t9iAw'
