
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-17T13:34:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "66a7e7acb209c54eef9906c43a221dc207aa6072",
 "version": "0.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
