
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cb29ab3fa564eb1d47820d1d820e8107b0ce599e",
 "version": "0.post.dev699"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
