heat_template_version: ocata

description: >
  Configure sshd_config

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  BannerText:
    default: ''
    description: Configures Banner text in sshd_config
    type: string

outputs:
  role_data:
    description: Role data for the ssh
    value:
      service_name: sshd
      config_settings:
        BannerText: {get_param: BannerText}
      step_config: |
        include ::tripleo::profile::base::sshd
