document: meta-test
version: 1
name: ngnix
modulemd-url: https://raw.githubusercontent.com/container-images/nginx/master/nginx.yaml
service:
    port: 80
testdependencies:
    rpms:
        - curl
module:
    docker:
        start: "docker run -p 80:80 -v `pwd`/html_pages:/usr/share/nginx/html/:Z"
        container: docker.io/modularitycontainers/nginx
    rpm:
        start: systemctl start ngnix
        stop: systemctl stop ngnix
        status: systemctl status ngnix
        repo: "http://mirror.vutbr.cz/fedora/releases/25/Everything/x86_64/os/"
test:
    ngnix_is_running:
        - 'ls  /proc/*/exe -alh | grep ngnix'
testhost:
    grep_index_html:
        'curl http://localhost:80 | grep superfirstpage'
