# This file was auto-generated by salt's setup on Tuesday, 15 August 2017 @ 15:08:35 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2016, 3, 7, 0, 0, 0, None)
