from ...tl.tlobject import TLObject


class PrivacyValueDisallowContacts(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    privacyValueDisallowContacts#f888fa1a = PrivacyRule"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xf888fa1a
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xebb7f270

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(PrivacyValueDisallowContacts.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return PrivacyValueDisallowContacts()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'privacyValueDisallowContacts#f888fa1a = PrivacyRule'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
