from ...tl.tlobject import TLObject


class RpcAnswerUnknown(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    rpc_answer_unknown#5e2ad36e = RpcDropAnswer"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x5e2ad36e
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x4bca7570

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(RpcAnswerUnknown.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return RpcAnswerUnknown()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'rpc_answer_unknown#5e2ad36e = RpcDropAnswer'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
