
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-23T09:41:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3820191ddb9a36922df7f96db548e8ec083ae702",
 "version": "2.11.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
