---
metadata:
    processor: XMLParser
    execute:
        - method: _rpc
          kwargs:
              get: "<get-configuration/>"

interfaces:
    _process:
        - path: "configuration.interfaces"
          from: root_interfaces.0
    interface:
        _process:
            - path: "interface"
              key: name
        name:
            _process: unnecessary
        hold-time:
            _process: not_implemented
            config:
                _process: not_implemented
                down:
                    _process: not_implemented
                up:
                    _process: not_implemented
        config:
            _process: unnecessary
            name:
                _process:
                    - value: "{{ interface_key }}"
            type:
                _process:
                    - mode: map
                      path: name
                      regexp: "(?P<value>[a-z]+).*"
                      map:
                          ge: ethernetCsmacd
                          xe: ethernetCsmacd
                          et: ethernetCsmacd
                          irb: ethernetCsmacd
                          me: ethernetCsmacd
                          vlan: ethernetCsmacd
                          lo: softwareLoopback
                          ae: ieee8023adLag
            enabled:
                _process:
                    - mode: is_absent
                      path: "disable"
            description:
                _process:
                    - path: description
            mtu:
                _process:
                    - path: mtu
        subinterfaces:
            _process: unnecessary
            subinterface:
                _process:
                    - path: "unit"
                      key: name
                index:
                    _process: unnecessary
                config:
                    _process: unnecessary
                    index:
                        _process: not_implemented
                    name:
                        _process:
                            - value: "{{ subinterface_key }}"
                    enabled:
                        _process:
                            - mode: is_absent
                              path: "disable"
                    description:
                        _process:
                            - path: description
