database:
    type: FireBase

    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    projectId: studio-ed756
    messagingSenderId: 81790704397

    authDomain: "{}.firebaseapp.com"
    databaseURL: "https://{}.firebaseio.com"
    storageBucket: "{}.appspot.com"

    # serviceAccount: "/path/to/serviceAccount.json"
    # guest: true
    # use_email_auth: true



# storage:
    # type: gcloud
    # bucket: "studio-ed756.appspot.com"

queue: local

saveWorkspaceFrequencyMinutes: 1
verbose: error

cloud:
    type: google
    zone: us-central1-f

    cpus: 2
    ram:  3g
    hdd:  10g
    gpus: 0

sleep_time: 1
worker_timeout: 30
