
'''
This file is automatically generated by setup.py, So don't edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.12.3.post1',
    'branch_nick': '(detached',
    'revision_id': '132481ecb9ae190d0e93a71a5ad1842481ba6abb',
    'revno': 5234
}
