# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bclient/ui/wbubble.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WBubble(object):
    def setupUi(self, WBubble):
        WBubble.setObjectName("WBubble")
        WBubble.resize(847, 935)
        WBubble.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(WBubble)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(WBubble)
        self.tabWidget.setObjectName("tabWidget")
        self.serverTab = QtWidgets.QWidget()
        self.serverTab.setObjectName("serverTab")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.serverTab)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.groupBox = QtWidgets.QGroupBox(self.serverTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.localCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.localCheckBox.setObjectName("localCheckBox")
        self.horizontalLayout_15.addWidget(self.localCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.hostLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.horizontalLayout_13.addWidget(self.hostLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.portSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.portSpinBox.setMinimum(1025)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 8587)
        self.portSpinBox.setObjectName("portSpinBox")
        self.horizontalLayout_12.addWidget(self.portSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.speedCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.speedCheckBox.setObjectName("speedCheckBox")
        self.horizontalLayout_35.addWidget(self.speedCheckBox)
        self.sspeedCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.sspeedCheckBox.setObjectName("sspeedCheckBox")
        self.horizontalLayout_35.addWidget(self.sspeedCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.serverLampLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(21)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.serverLampLabel.sizePolicy().hasHeightForWidth())
        self.serverLampLabel.setSizePolicy(sizePolicy)
        self.serverLampLabel.setMinimumSize(QtCore.QSize(21, 21))
        self.serverLampLabel.setMaximumSize(QtCore.QSize(21, 21))
        self.serverLampLabel.setText("")
        self.serverLampLabel.setPixmap(QtGui.QPixmap(":/redbtn"))
        self.serverLampLabel.setScaledContents(True)
        self.serverLampLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.serverLampLabel.setObjectName("serverLampLabel")
        self.horizontalLayout_16.addWidget(self.serverLampLabel)
        self.serverStateLabel = QtWidgets.QLabel(self.groupBox)
        self.serverStateLabel.setObjectName("serverStateLabel")
        self.horizontalLayout_16.addWidget(self.serverStateLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.snblRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.snblRadio.setObjectName("snblRadio")
        self.horizontalLayout_9.addWidget(self.snblRadio)
        self.dubbleRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.dubbleRadio.setChecked(True)
        self.dubbleRadio.setObjectName("dubbleRadio")
        self.horizontalLayout_9.addWidget(self.dubbleRadio)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.qRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.qRadio.setChecked(True)
        self.qRadio.setObjectName("qRadio")
        self.horizontalLayout_30.addWidget(self.qRadio)
        self.tthRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.tthRadio.setObjectName("tthRadio")
        self.horizontalLayout_30.addWidget(self.tthRadio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.subdirCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.subdirCheckBox.setObjectName("subdirCheckBox")
        self.horizontalLayout_31.addWidget(self.subdirCheckBox)
        self.subdirEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.subdirEdit.setEnabled(False)
        self.subdirEdit.setObjectName("subdirEdit")
        self.horizontalLayout_31.addWidget(self.subdirEdit)
        self.extCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.extCheckBox.setObjectName("extCheckBox")
        self.horizontalLayout_31.addWidget(self.extCheckBox)
        self.extEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.extEdit.setEnabled(False)
        self.extEdit.setObjectName("extEdit")
        self.horizontalLayout_31.addWidget(self.extEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.multiCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.multiCheckBox.setObjectName("multiCheckBox")
        self.horizontalLayout_32.addWidget(self.multiCheckBox)
        self.multiEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.multiEdit.setObjectName("multiEdit")
        self.horizontalLayout_32.addWidget(self.multiEdit)
        self.edfCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.edfCheckBox.setObjectName("edfCheckBox")
        self.horizontalLayout_32.addWidget(self.edfCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.killServerButton = QtWidgets.QPushButton(self.groupBox)
        self.killServerButton.setObjectName("killServerButton")
        self.horizontalLayout_14.addWidget(self.killServerButton)
        self.stopServerButton = QtWidgets.QPushButton(self.groupBox)
        self.stopServerButton.setObjectName("stopServerButton")
        self.horizontalLayout_14.addWidget(self.stopServerButton)
        self.runServerButton = QtWidgets.QPushButton(self.groupBox)
        self.runServerButton.setObjectName("runServerButton")
        self.horizontalLayout_14.addWidget(self.runServerButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_25.addWidget(self.groupBox)
        self.tabWidget.addTab(self.serverTab, "")
        self.saxsTab = QtWidgets.QWidget()
        self.saxsTab.setObjectName("saxsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.saxsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.saxsTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.saxsLampLabel = QtWidgets.QLabel(self.saxsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(21)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.saxsLampLabel.sizePolicy().hasHeightForWidth())
        self.saxsLampLabel.setSizePolicy(sizePolicy)
        self.saxsLampLabel.setMinimumSize(QtCore.QSize(21, 21))
        self.saxsLampLabel.setMaximumSize(QtCore.QSize(21, 21))
        self.saxsLampLabel.setText("")
        self.saxsLampLabel.setPixmap(QtGui.QPixmap(":/redbtn"))
        self.saxsLampLabel.setScaledContents(True)
        self.saxsLampLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.saxsLampLabel.setObjectName("saxsLampLabel")
        self.horizontalLayout_3.addWidget(self.saxsLampLabel)
        self.saxsStateLabel = QtWidgets.QLabel(self.saxsTab)
        self.saxsStateLabel.setObjectName("saxsStateLabel")
        self.horizontalLayout_3.addWidget(self.saxsStateLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.saxsTab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.saxsLastfileLabel = QtWidgets.QLabel(self.saxsTab)
        self.saxsLastfileLabel.setObjectName("saxsLastfileLabel")
        self.horizontalLayout_4.addWidget(self.saxsLastfileLabel)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_8 = QtWidgets.QLabel(self.saxsTab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_24.addWidget(self.label_8)
        self.saxsTotalLabel = QtWidgets.QLabel(self.saxsTab)
        self.saxsTotalLabel.setObjectName("saxsTotalLabel")
        self.horizontalLayout_24.addWidget(self.saxsTotalLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.line_2 = QtWidgets.QFrame(self.saxsTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.saxsTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.saxsDetectorComboBox = QtWidgets.QComboBox(self.saxsTab)
        self.saxsDetectorComboBox.setObjectName("saxsDetectorComboBox")
        self.saxsDetectorComboBox.addItem("")
        self.saxsDetectorComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.saxsDetectorComboBox)
        self.darkFilesButton = QtWidgets.QPushButton(self.saxsTab)
        self.darkFilesButton.setObjectName("darkFilesButton")
        self.horizontalLayout_7.addWidget(self.darkFilesButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.saxsTab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.saxsDirLineEdit = QtWidgets.QLineEdit(self.saxsTab)
        self.saxsDirLineEdit.setObjectName("saxsDirLineEdit")
        self.horizontalLayout_6.addWidget(self.saxsDirLineEdit)
        self.saxsFolderButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsFolderButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/folder"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saxsFolderButton.setIcon(icon)
        self.saxsFolderButton.setObjectName("saxsFolderButton")
        self.horizontalLayout_6.addWidget(self.saxsFolderButton)
        self.saxsDirClearButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsDirClearButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/clear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saxsDirClearButton.setIcon(icon1)
        self.saxsDirClearButton.setObjectName("saxsDirClearButton")
        self.horizontalLayout_6.addWidget(self.saxsDirClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_16 = QtWidgets.QLabel(self.saxsTab)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.saxsPoniLineEdit = QtWidgets.QLineEdit(self.saxsTab)
        self.saxsPoniLineEdit.setObjectName("saxsPoniLineEdit")
        self.horizontalLayout_21.addWidget(self.saxsPoniLineEdit)
        self.saxsPoniButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsPoniButton.setText("")
        self.saxsPoniButton.setIcon(icon)
        self.saxsPoniButton.setObjectName("saxsPoniButton")
        self.horizontalLayout_21.addWidget(self.saxsPoniButton)
        self.saxsPoniClearButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsPoniClearButton.setText("")
        self.saxsPoniClearButton.setIcon(icon1)
        self.saxsPoniClearButton.setObjectName("saxsPoniClearButton")
        self.horizontalLayout_21.addWidget(self.saxsPoniClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.saxsTab)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_27.addWidget(self.label_20)
        self.saxsMaskLineEdit = QtWidgets.QLineEdit(self.saxsTab)
        self.saxsMaskLineEdit.setObjectName("saxsMaskLineEdit")
        self.horizontalLayout_27.addWidget(self.saxsMaskLineEdit)
        self.saxsMaskButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsMaskButton.setText("")
        self.saxsMaskButton.setIcon(icon)
        self.saxsMaskButton.setObjectName("saxsMaskButton")
        self.horizontalLayout_27.addWidget(self.saxsMaskButton)
        self.saxsMakeMaskButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsMakeMaskButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/mask"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saxsMakeMaskButton.setIcon(icon2)
        self.saxsMakeMaskButton.setObjectName("saxsMakeMaskButton")
        self.horizontalLayout_27.addWidget(self.saxsMakeMaskButton)
        self.saxsMaskClearButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsMaskClearButton.setText("")
        self.saxsMaskClearButton.setIcon(icon1)
        self.saxsMaskClearButton.setObjectName("saxsMaskClearButton")
        self.horizontalLayout_27.addWidget(self.saxsMaskClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.saxsTab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.saxsBkgLineEdit = QtWidgets.QLineEdit(self.saxsTab)
        self.saxsBkgLineEdit.setObjectName("saxsBkgLineEdit")
        self.horizontalLayout_23.addWidget(self.saxsBkgLineEdit)
        self.saxsBkgButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsBkgButton.setText("")
        self.saxsBkgButton.setIcon(icon)
        self.saxsBkgButton.setObjectName("saxsBkgButton")
        self.horizontalLayout_23.addWidget(self.saxsBkgButton)
        self.saxsBkgClearButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsBkgClearButton.setText("")
        self.saxsBkgClearButton.setIcon(icon1)
        self.saxsBkgClearButton.setObjectName("saxsBkgClearButton")
        self.horizontalLayout_23.addWidget(self.saxsBkgClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.saxsTab)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.saxsBkgCoefSpinBox = QtWidgets.QDoubleSpinBox(self.saxsTab)
        self.saxsBkgCoefSpinBox.setDecimals(4)
        self.saxsBkgCoefSpinBox.setMaximum(1000000.0)
        self.saxsBkgCoefSpinBox.setObjectName("saxsBkgCoefSpinBox")
        self.horizontalLayout_22.addWidget(self.saxsBkgCoefSpinBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.saxsAzimuthCheckBox = QtWidgets.QCheckBox(self.saxsTab)
        self.saxsAzimuthCheckBox.setObjectName("saxsAzimuthCheckBox")
        self.horizontalLayout_36.addWidget(self.saxsAzimuthCheckBox)
        self.saxsAziStartSpinBox = QtWidgets.QDoubleSpinBox(self.saxsTab)
        self.saxsAziStartSpinBox.setMaximum(360.0)
        self.saxsAziStartSpinBox.setObjectName("saxsAziStartSpinBox")
        self.horizontalLayout_36.addWidget(self.saxsAziStartSpinBox)
        self.label_26 = QtWidgets.QLabel(self.saxsTab)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_36.addWidget(self.label_26)
        self.saxsAziStopSpinBox = QtWidgets.QDoubleSpinBox(self.saxsTab)
        self.saxsAziStopSpinBox.setMaximum(360.0)
        self.saxsAziStopSpinBox.setObjectName("saxsAziStopSpinBox")
        self.horizontalLayout_36.addWidget(self.saxsAziStopSpinBox)
        self.saxsSlicesCheckBox = QtWidgets.QCheckBox(self.saxsTab)
        self.saxsSlicesCheckBox.setObjectName("saxsSlicesCheckBox")
        self.horizontalLayout_36.addWidget(self.saxsSlicesCheckBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.saxsRadialCheckBox = QtWidgets.QCheckBox(self.saxsTab)
        self.saxsRadialCheckBox.setObjectName("saxsRadialCheckBox")
        self.horizontalLayout_38.addWidget(self.saxsRadialCheckBox)
        self.saxsRadStartSpinBox = QtWidgets.QDoubleSpinBox(self.saxsTab)
        self.saxsRadStartSpinBox.setMaximum(360.0)
        self.saxsRadStartSpinBox.setObjectName("saxsRadStartSpinBox")
        self.horizontalLayout_38.addWidget(self.saxsRadStartSpinBox)
        self.label_28 = QtWidgets.QLabel(self.saxsTab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_38.addWidget(self.label_28)
        self.saxsRadStopSpinBox = QtWidgets.QDoubleSpinBox(self.saxsTab)
        self.saxsRadStopSpinBox.setMaximum(360.0)
        self.saxsRadStopSpinBox.setObjectName("saxsRadStopSpinBox")
        self.horizontalLayout_38.addWidget(self.saxsRadStopSpinBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_38)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.saxsPlotButton = QtWidgets.QPushButton(self.saxsTab)
        self.saxsPlotButton.setCheckable(True)
        self.saxsPlotButton.setChecked(False)
        self.saxsPlotButton.setObjectName("saxsPlotButton")
        self.horizontalLayout_20.addWidget(self.saxsPlotButton)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.advancedButton = QtWidgets.QPushButton(self.saxsTab)
        self.advancedButton.setObjectName("advancedButton")
        self.horizontalLayout_20.addWidget(self.advancedButton)
        self.runSaxsButton = QtWidgets.QPushButton(self.saxsTab)
        self.runSaxsButton.setObjectName("runSaxsButton")
        self.horizontalLayout_20.addWidget(self.runSaxsButton)
        self.stopSaxsButton = QtWidgets.QPushButton(self.saxsTab)
        self.stopSaxsButton.setObjectName("stopSaxsButton")
        self.horizontalLayout_20.addWidget(self.stopSaxsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.line_2.raise_()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/redbtn"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.saxsTab, icon3, "")
        self.waxsTab = QtWidgets.QWidget()
        self.waxsTab.setObjectName("waxsTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.waxsTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.waxsTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.waxsLampLabel = QtWidgets.QLabel(self.waxsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(21)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(self.waxsLampLabel.sizePolicy().hasHeightForWidth())
        self.waxsLampLabel.setSizePolicy(sizePolicy)
        self.waxsLampLabel.setMinimumSize(QtCore.QSize(21, 21))
        self.waxsLampLabel.setMaximumSize(QtCore.QSize(21, 21))
        self.waxsLampLabel.setText("")
        self.waxsLampLabel.setPixmap(QtGui.QPixmap(":/redbtn"))
        self.waxsLampLabel.setScaledContents(True)
        self.waxsLampLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.waxsLampLabel.setObjectName("waxsLampLabel")
        self.horizontalLayout.addWidget(self.waxsLampLabel)
        self.waxsStateLabel = QtWidgets.QLabel(self.waxsTab)
        self.waxsStateLabel.setObjectName("waxsStateLabel")
        self.horizontalLayout.addWidget(self.waxsStateLabel)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.waxsTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.waxsLastfileLabel = QtWidgets.QLabel(self.waxsTab)
        self.waxsLastfileLabel.setObjectName("waxsLastfileLabel")
        self.horizontalLayout_2.addWidget(self.waxsLastfileLabel)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.waxsTab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.waxsTotalLabel = QtWidgets.QLabel(self.waxsTab)
        self.waxsTotalLabel.setObjectName("waxsTotalLabel")
        self.horizontalLayout_11.addWidget(self.waxsTotalLabel)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.line = QtWidgets.QFrame(self.waxsTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_23 = QtWidgets.QLabel(self.waxsTab)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_33.addWidget(self.label_23)
        self.waxsDetectorComboBox = QtWidgets.QComboBox(self.waxsTab)
        self.waxsDetectorComboBox.setObjectName("waxsDetectorComboBox")
        self.waxsDetectorComboBox.addItem("")
        self.waxsDetectorComboBox.addItem("")
        self.horizontalLayout_33.addWidget(self.waxsDetectorComboBox)
        self.waxsDarkFilesButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsDarkFilesButton.setObjectName("waxsDarkFilesButton")
        self.horizontalLayout_33.addWidget(self.waxsDarkFilesButton)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.waxsTab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.waxsDirLineEdit = QtWidgets.QLineEdit(self.waxsTab)
        self.waxsDirLineEdit.setObjectName("waxsDirLineEdit")
        self.horizontalLayout_5.addWidget(self.waxsDirLineEdit)
        self.waxsFolderButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsFolderButton.setText("")
        self.waxsFolderButton.setIcon(icon)
        self.waxsFolderButton.setObjectName("waxsFolderButton")
        self.horizontalLayout_5.addWidget(self.waxsFolderButton)
        self.waxsDirClearButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsDirClearButton.setText("")
        self.waxsDirClearButton.setIcon(icon1)
        self.waxsDirClearButton.setObjectName("waxsDirClearButton")
        self.horizontalLayout_5.addWidget(self.waxsDirClearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.waxsTab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.waxsPoniLineEdit = QtWidgets.QLineEdit(self.waxsTab)
        self.waxsPoniLineEdit.setObjectName("waxsPoniLineEdit")
        self.horizontalLayout_10.addWidget(self.waxsPoniLineEdit)
        self.waxsPoniButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsPoniButton.setText("")
        self.waxsPoniButton.setIcon(icon)
        self.waxsPoniButton.setObjectName("waxsPoniButton")
        self.horizontalLayout_10.addWidget(self.waxsPoniButton)
        self.waxsPoniClearButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsPoniClearButton.setText("")
        self.waxsPoniClearButton.setIcon(icon1)
        self.waxsPoniClearButton.setObjectName("waxsPoniClearButton")
        self.horizontalLayout_10.addWidget(self.waxsPoniClearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_22 = QtWidgets.QLabel(self.waxsTab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_29.addWidget(self.label_22)
        self.waxsMaskLineEdit = QtWidgets.QLineEdit(self.waxsTab)
        self.waxsMaskLineEdit.setObjectName("waxsMaskLineEdit")
        self.horizontalLayout_29.addWidget(self.waxsMaskLineEdit)
        self.waxsMaskButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsMaskButton.setText("")
        self.waxsMaskButton.setIcon(icon)
        self.waxsMaskButton.setObjectName("waxsMaskButton")
        self.horizontalLayout_29.addWidget(self.waxsMaskButton)
        self.waxsMakeMaskButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsMakeMaskButton.setText("")
        self.waxsMakeMaskButton.setIcon(icon2)
        self.waxsMakeMaskButton.setObjectName("waxsMakeMaskButton")
        self.horizontalLayout_29.addWidget(self.waxsMakeMaskButton)
        self.waxsMaskClearButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsMaskClearButton.setText("")
        self.waxsMaskClearButton.setIcon(icon1)
        self.waxsMaskClearButton.setObjectName("waxsMaskClearButton")
        self.horizontalLayout_29.addWidget(self.waxsMaskClearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.waxsTab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.waxsBkgLineEdit = QtWidgets.QLineEdit(self.waxsTab)
        self.waxsBkgLineEdit.setObjectName("waxsBkgLineEdit")
        self.horizontalLayout_18.addWidget(self.waxsBkgLineEdit)
        self.waxsBkgButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsBkgButton.setText("")
        self.waxsBkgButton.setIcon(icon)
        self.waxsBkgButton.setObjectName("waxsBkgButton")
        self.horizontalLayout_18.addWidget(self.waxsBkgButton)
        self.waxsBkgClearButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsBkgClearButton.setText("")
        self.waxsBkgClearButton.setIcon(icon1)
        self.waxsBkgClearButton.setObjectName("waxsBkgClearButton")
        self.horizontalLayout_18.addWidget(self.waxsBkgClearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.waxsTab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.waxsBkgCoefSpinBox = QtWidgets.QDoubleSpinBox(self.waxsTab)
        self.waxsBkgCoefSpinBox.setDecimals(4)
        self.waxsBkgCoefSpinBox.setMaximum(1000000.0)
        self.waxsBkgCoefSpinBox.setObjectName("waxsBkgCoefSpinBox")
        self.horizontalLayout_19.addWidget(self.waxsBkgCoefSpinBox)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_21 = QtWidgets.QLabel(self.waxsTab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_28.addWidget(self.label_21)
        self.multiplyLineEdit = QtWidgets.QLineEdit(self.waxsTab)
        self.multiplyLineEdit.setObjectName("multiplyLineEdit")
        self.horizontalLayout_28.addWidget(self.multiplyLineEdit)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem21)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.waxsAzimuthCheckBox = QtWidgets.QCheckBox(self.waxsTab)
        self.waxsAzimuthCheckBox.setObjectName("waxsAzimuthCheckBox")
        self.horizontalLayout_34.addWidget(self.waxsAzimuthCheckBox)
        self.waxsAziStartSpinBox = QtWidgets.QDoubleSpinBox(self.waxsTab)
        self.waxsAziStartSpinBox.setMaximum(360.0)
        self.waxsAziStartSpinBox.setObjectName("waxsAziStartSpinBox")
        self.horizontalLayout_34.addWidget(self.waxsAziStartSpinBox)
        self.label_25 = QtWidgets.QLabel(self.waxsTab)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_34.addWidget(self.label_25)
        self.waxsAziStopSpinBox = QtWidgets.QDoubleSpinBox(self.waxsTab)
        self.waxsAziStopSpinBox.setMaximum(360.0)
        self.waxsAziStopSpinBox.setObjectName("waxsAziStopSpinBox")
        self.horizontalLayout_34.addWidget(self.waxsAziStopSpinBox)
        self.waxsSlicesCheckBox = QtWidgets.QCheckBox(self.waxsTab)
        self.waxsSlicesCheckBox.setObjectName("waxsSlicesCheckBox")
        self.horizontalLayout_34.addWidget(self.waxsSlicesCheckBox)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.waxsRadialCheckBox = QtWidgets.QCheckBox(self.waxsTab)
        self.waxsRadialCheckBox.setObjectName("waxsRadialCheckBox")
        self.horizontalLayout_37.addWidget(self.waxsRadialCheckBox)
        self.waxsRadStartSpinBox = QtWidgets.QDoubleSpinBox(self.waxsTab)
        self.waxsRadStartSpinBox.setMaximum(360.0)
        self.waxsRadStartSpinBox.setObjectName("waxsRadStartSpinBox")
        self.horizontalLayout_37.addWidget(self.waxsRadStartSpinBox)
        self.label_27 = QtWidgets.QLabel(self.waxsTab)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_37.addWidget(self.label_27)
        self.waxsRadStopSpinBox = QtWidgets.QDoubleSpinBox(self.waxsTab)
        self.waxsRadStopSpinBox.setMaximum(360.0)
        self.waxsRadStopSpinBox.setObjectName("waxsRadStopSpinBox")
        self.horizontalLayout_37.addWidget(self.waxsRadStopSpinBox)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_6 = QtWidgets.QLabel(self.waxsTab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_26.addWidget(self.label_6)
        self.radioNormNone = QtWidgets.QRadioButton(self.waxsTab)
        self.radioNormNone.setObjectName("radioNormNone")
        self.horizontalLayout_26.addWidget(self.radioNormNone)
        self.radioNormMon = QtWidgets.QRadioButton(self.waxsTab)
        self.radioNormMon.setChecked(True)
        self.radioNormMon.setObjectName("radioNormMon")
        self.horizontalLayout_26.addWidget(self.radioNormMon)
        self.radioNormBkg = QtWidgets.QRadioButton(self.waxsTab)
        self.radioNormBkg.setObjectName("radioNormBkg")
        self.horizontalLayout_26.addWidget(self.radioNormBkg)
        self.editNormMin = QtWidgets.QLineEdit(self.waxsTab)
        self.editNormMin.setEnabled(False)
        self.editNormMin.setObjectName("editNormMin")
        self.horizontalLayout_26.addWidget(self.editNormMin)
        self.editNormMax = QtWidgets.QLineEdit(self.waxsTab)
        self.editNormMax.setEnabled(False)
        self.editNormMax.setObjectName("editNormMax")
        self.horizontalLayout_26.addWidget(self.editNormMax)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem24)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.waxsPlotButton = QtWidgets.QPushButton(self.waxsTab)
        self.waxsPlotButton.setCheckable(True)
        self.waxsPlotButton.setChecked(False)
        self.waxsPlotButton.setObjectName("waxsPlotButton")
        self.horizontalLayout_17.addWidget(self.waxsPlotButton)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem25)
        self.runWaxsButton = QtWidgets.QPushButton(self.waxsTab)
        self.runWaxsButton.setObjectName("runWaxsButton")
        self.horizontalLayout_17.addWidget(self.runWaxsButton)
        self.stopWaxsButton = QtWidgets.QPushButton(self.waxsTab)
        self.stopWaxsButton.setObjectName("stopWaxsButton")
        self.horizontalLayout_17.addWidget(self.stopWaxsButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.waxsTab, icon3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.aboutButton = QtWidgets.QPushButton(WBubble)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout_8.addWidget(self.aboutButton)
        self.saveButton = QtWidgets.QPushButton(WBubble)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_8.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(WBubble)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_8.addWidget(self.loadButton)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.exitButton = QtWidgets.QPushButton(WBubble)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_8.addWidget(self.exitButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.label_10.setBuddy(self.hostLineEdit)
        self.label_9.setBuddy(self.portSpinBox)
        self.label_20.setBuddy(self.saxsMaskLineEdit)
        self.label_11.setBuddy(self.waxsDirLineEdit)
        self.label_13.setBuddy(self.waxsPoniLineEdit)
        self.label_22.setBuddy(self.saxsMaskLineEdit)
        self.label_14.setBuddy(self.waxsBkgLineEdit)
        self.label_15.setBuddy(self.waxsBkgCoefSpinBox)

        self.retranslateUi(WBubble)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(WBubble)

    def retranslateUi(self, WBubble):
        _translate = QtCore.QCoreApplication.translate
        WBubble.setWindowTitle(_translate("WBubble", "Bubble client"))
        self.groupBox.setTitle(_translate("WBubble", "Server setup"))
        self.localCheckBox.setText(_translate("WBubble", "Run server locally"))
        self.label_10.setText(_translate("WBubble", "Server &host:"))
        self.hostLineEdit.setText(_translate("WBubble", "localhost"))
        self.label_9.setText(_translate("WBubble", "Server &port:"))
        self.speedCheckBox.setText(_translate("WBubble", "Optimize for speed (no images)"))
        self.sspeedCheckBox.setText(_translate("WBubble", "Super speed (no control)"))
        self.serverStateLabel.setText(_translate("WBubble", "Server is stopped"))
        self.groupBox_3.setTitle(_translate("WBubble", "The beam line"))
        self.snblRadio.setText(_translate("WBubble", "SNBL"))
        self.dubbleRadio.setText(_translate("WBubble", "Dubble"))
        self.groupBox_2.setTitle(_translate("WBubble", "Output"))
        self.qRadio.setText(_translate("WBubble", "Q (nm⁻ⁱ)"))
        self.tthRadio.setText(_translate("WBubble", "2θ⁰"))
        self.subdirCheckBox.setText(_translate("WBubble", "Subfolder"))
        self.extCheckBox.setText(_translate("WBubble", "Extension"))
        self.multiCheckBox.setText(_translate("WBubble", "Multicolumn"))
        self.edfCheckBox.setText(_translate("WBubble", "Normalized EDF"))
        self.killServerButton.setText(_translate("WBubble", "Stop server"))
        self.stopServerButton.setText(_translate("WBubble", "Disconnect"))
        self.runServerButton.setText(_translate("WBubble", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serverTab), _translate("WBubble", "Server"))
        self.label_3.setText(_translate("WBubble", "State:"))
        self.saxsStateLabel.setText(_translate("WBubble", "stopped"))
        self.label_4.setText(_translate("WBubble", "Last file:"))
        self.saxsLastfileLabel.setText(_translate("WBubble", "unknown"))
        self.label_8.setText(_translate("WBubble", "Total:"))
        self.saxsTotalLabel.setText(_translate("WBubble", "0"))
        self.label_5.setText(_translate("WBubble", "Detector:"))
        self.saxsDetectorComboBox.setItemText(0, _translate("WBubble", "Pilatus"))
        self.saxsDetectorComboBox.setItemText(1, _translate("WBubble", "Frelon"))
        self.darkFilesButton.setText(_translate("WBubble", "Dark files"))
        self.label_12.setText(_translate("WBubble", "Folder:"))
        self.label_16.setText(_translate("WBubble", "Poni:"))
        self.label_20.setText(_translate("WBubble", "&Mask:"))
        self.label_18.setText(_translate("WBubble", "Background:"))
        self.label_17.setText(_translate("WBubble", "Background coefficient:"))
        self.saxsAzimuthCheckBox.setText(_translate("WBubble", "Azimuth start"))
        self.label_26.setText(_translate("WBubble", "and stop"))
        self.saxsSlicesCheckBox.setText(_translate("WBubble", "slices"))
        self.saxsRadialCheckBox.setText(_translate("WBubble", "Radial start"))
        self.label_28.setText(_translate("WBubble", "and stop"))
        self.saxsPlotButton.setText(_translate("WBubble", "Plot"))
        self.advancedButton.setText(_translate("WBubble", "Advanced"))
        self.runSaxsButton.setText(_translate("WBubble", "Run SAXS"))
        self.stopSaxsButton.setText(_translate("WBubble", "Stop SAXS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saxsTab), _translate("WBubble", "SAXS"))
        self.label.setText(_translate("WBubble", "State:"))
        self.waxsStateLabel.setText(_translate("WBubble", "stopped"))
        self.label_2.setText(_translate("WBubble", "Last file:"))
        self.waxsLastfileLabel.setText(_translate("WBubble", "unknown"))
        self.label_7.setText(_translate("WBubble", "Total:"))
        self.waxsTotalLabel.setText(_translate("WBubble", "0"))
        self.label_23.setText(_translate("WBubble", "Detector:"))
        self.waxsDetectorComboBox.setItemText(0, _translate("WBubble", "Pilatus"))
        self.waxsDetectorComboBox.setItemText(1, _translate("WBubble", "Frelon"))
        self.waxsDarkFilesButton.setText(_translate("WBubble", "Dark files"))
        self.label_11.setText(_translate("WBubble", "&Folder:"))
        self.label_13.setText(_translate("WBubble", "&Poni:"))
        self.label_22.setText(_translate("WBubble", "&Mask:"))
        self.label_14.setText(_translate("WBubble", "&Background:"))
        self.label_15.setText(_translate("WBubble", "Background &coefficient:"))
        self.label_21.setText(_translate("WBubble", "Multiply:"))
        self.waxsAzimuthCheckBox.setText(_translate("WBubble", "Azimuth start"))
        self.label_25.setText(_translate("WBubble", "and stop"))
        self.waxsSlicesCheckBox.setText(_translate("WBubble", "slices"))
        self.waxsRadialCheckBox.setText(_translate("WBubble", "Radial start"))
        self.label_27.setText(_translate("WBubble", "and stop"))
        self.label_6.setText(_translate("WBubble", "Normalize:"))
        self.radioNormNone.setText(_translate("WBubble", "None"))
        self.radioNormMon.setText(_translate("WBubble", "Monitor"))
        self.radioNormBkg.setText(_translate("WBubble", "Background"))
        self.waxsPlotButton.setText(_translate("WBubble", "Plot"))
        self.runWaxsButton.setText(_translate("WBubble", "Run WAXS"))
        self.stopWaxsButton.setText(_translate("WBubble", "Stop WAXS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.waxsTab), _translate("WBubble", "WAXS"))
        self.aboutButton.setText(_translate("WBubble", "About"))
        self.saveButton.setText(_translate("WBubble", "Save..."))
        self.loadButton.setText(_translate("WBubble", "Load..."))
        self.exitButton.setText(_translate("WBubble", "Exit"))

from . import resources_rc
