# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bclient/ui/wdark.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WDark(object):
    def setupUi(self, WDark):
        WDark.setObjectName("WDark")
        WDark.resize(613, 356)
        WDark.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(WDark)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(WDark)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bkgLineEdit = QtWidgets.QLineEdit(WDark)
        self.bkgLineEdit.setText("")
        self.bkgLineEdit.setObjectName("bkgLineEdit")
        self.horizontalLayout.addWidget(self.bkgLineEdit)
        self.bkgButton = QtWidgets.QPushButton(WDark)
        self.bkgButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/folder"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bkgButton.setIcon(icon)
        self.bkgButton.setObjectName("bkgButton")
        self.horizontalLayout.addWidget(self.bkgButton)
        self.bkgClearButton = QtWidgets.QPushButton(WDark)
        self.bkgClearButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/clear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bkgClearButton.setIcon(icon1)
        self.bkgClearButton.setObjectName("bkgClearButton")
        self.horizontalLayout.addWidget(self.bkgClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(WDark)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sampleLineEdit = QtWidgets.QLineEdit(WDark)
        self.sampleLineEdit.setText("")
        self.sampleLineEdit.setObjectName("sampleLineEdit")
        self.horizontalLayout_2.addWidget(self.sampleLineEdit)
        self.sampleButton = QtWidgets.QPushButton(WDark)
        self.sampleButton.setText("")
        self.sampleButton.setIcon(icon)
        self.sampleButton.setObjectName("sampleButton")
        self.horizontalLayout_2.addWidget(self.sampleButton)
        self.sampleClearButton = QtWidgets.QPushButton(WDark)
        self.sampleClearButton.setText("")
        self.sampleClearButton.setIcon(icon1)
        self.sampleClearButton.setObjectName("sampleClearButton")
        self.horizontalLayout_2.addWidget(self.sampleClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(WDark)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.splineLineEdit = QtWidgets.QLineEdit(WDark)
        self.splineLineEdit.setText("")
        self.splineLineEdit.setObjectName("splineLineEdit")
        self.horizontalLayout_3.addWidget(self.splineLineEdit)
        self.splineButton = QtWidgets.QPushButton(WDark)
        self.splineButton.setText("")
        self.splineButton.setIcon(icon)
        self.splineButton.setObjectName("splineButton")
        self.horizontalLayout_3.addWidget(self.splineButton)
        self.splineClearButton = QtWidgets.QPushButton(WDark)
        self.splineClearButton.setText("")
        self.splineClearButton.setIcon(icon1)
        self.splineClearButton.setObjectName("splineClearButton")
        self.horizontalLayout_3.addWidget(self.splineClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(WDark)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.floodLineEdit = QtWidgets.QLineEdit(WDark)
        self.floodLineEdit.setText("")
        self.floodLineEdit.setObjectName("floodLineEdit")
        self.horizontalLayout_4.addWidget(self.floodLineEdit)
        self.floodButton = QtWidgets.QPushButton(WDark)
        self.floodButton.setText("")
        self.floodButton.setIcon(icon)
        self.floodButton.setObjectName("floodButton")
        self.horizontalLayout_4.addWidget(self.floodButton)
        self.floodClearButton = QtWidgets.QPushButton(WDark)
        self.floodClearButton.setText("")
        self.floodClearButton.setIcon(icon1)
        self.floodClearButton.setObjectName("floodClearButton")
        self.horizontalLayout_4.addWidget(self.floodClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.incidenceCheckBox = QtWidgets.QCheckBox(WDark)
        self.incidenceCheckBox.setObjectName("incidenceCheckBox")
        self.verticalLayout.addWidget(self.incidenceCheckBox)
        spacerItem = QtWidgets.QSpacerItem(17, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.okButton = QtWidgets.QPushButton(WDark)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_5.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(WDark)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(WDark)
        QtCore.QMetaObject.connectSlotsByName(WDark)

    def retranslateUi(self, WDark):
        _translate = QtCore.QCoreApplication.translate
        WDark.setWindowTitle(_translate("WDark", "Frelon corrections"))
        self.label.setText(_translate("WDark", "Dark background"))
        self.label_2.setText(_translate("WDark", "Dark sample"))
        self.label_3.setText(_translate("WDark", "Spline"))
        self.label_4.setText(_translate("WDark", "Flood"))
        self.incidenceCheckBox.setText(_translate("WDark", "Incidence angle correction (good for PDF)"))
        self.okButton.setText(_translate("WDark", "Apply"))
        self.cancelButton.setText(_translate("WDark", "Cancel"))

from . import resources_rc
