################## Local node configuration ############


# You can set this node in a specific group and so enable specific:
# * checks
# * asserters
# * collectors
# * answer in specific DNS queries
groups: []


# By default the node name will be it's hostname. I can be quite random
# so if you want to set a name that talk to you, you can set it in display_name
display_name: ""

# Datacenters: group of nodes (not used currently)
datacenters:
    - dc1

# In which zone to set the element
node-zone: internet

proxy-node: false


############################# Startup
bootstrap: false

# If set, at startup the node will try to join/synchronize with theses nodes
seeds: []

# Port to listen for UDP/HTTP connections
port: 6768

encryption_key: ""
master_key_priv: ""
master_key_pub: ""


# Where to store the daemon data
data: /var/lib/opsbro
lock: /var/run/opsbro.lock

socket: /var/lib/opsbro/opsbro.sock


########## Log
log: /var/log/opsbro
# Which level is the daemon running. Possible values are:
# * ERROR
# * WARNING
# * INFO
# * DEBUG
log_level: INFO


# Place to store nagios compatible plugins
libexec: /var/lib/opsbro/libexec/
