engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - "**.lib"
    - "**.sh"
    - "**.py"
exclude_paths:
  - docs/*
  - packages/grid_control/backends/htcondor_wms/*
  - packages/grid_control_cms/DashboardAPI/*
  - packages/grid_control_cms/Lexicon.py
  - packages/grid_control_cms/share/fragmentForCMSSW.py
  - packages/grid_control_gui/xmpp/*
  - packages/python_compat_json.py
  - packages/python_compat_tarfile.py
  - packages/python_compat_urllib2.py
  - packages/requests/*
