RECAST_STORAGEPATH: "/recastdata"
RECAST_RESULT_BASE: "/home/analysis/recast/recaststorage/results"
RECAST_GITHUBSECRET: ''
RECAST_ZENODO_TOKEN: ''
RECAST_SSL_CERTFILE: 'server.crt'
RECAST_SSL_KEYFILE: 'server.key'
RECAST_OAUTH_TOKENURL: 'https://oauth.web.cern.ch/OAuth/Token'
RECAST_OAUTH_AUTHORIZEURL: 'https://oauth.web.cern.ch/OAuth/Authorize'
RECAST_OAUTH_APPID: 'recastcontrol'
RECAST_OAUTH_SECRET: ''
RECAST_OAUTH_REDIRECT_ROUTE: '/oauth'
RECAST_BASEURL: https://recast-control.cern.ch
RECAST_SERVER_PORT: 8000
RECAST_OAUTH_DUMMYLOGIN: false
RECAST_CATALOGUE_FILE: /recastdata/catalogue.json