# coding: utf-8
# Generated by setup.py for PyCBC on 2017-08-17 23:32:21 +0000.

version = '1.7.8'
date = '2017-08-17 22:47:20 +0000'
release = True
last_release = '1.7.8'

git_hash = '4b7979eb94e3e512cbb8b5632d267850e7e0ba74'
git_branch = 'None'
git_tag = 'v1.7.8'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2017-08-17 23:32:21 +0000'
git_verbose_msg = """Branch: None
Tag: v1.7.8
Id: 4b7979eb94e3e512cbb8b5632d267850e7e0ba74
Builder: Unknown User <>
Build date: 2017-08-17 23:32:21 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
