# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='revision_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='head',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='revision_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
