
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-03T16:13:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f37d42a2b092d8b3ffa64100c9ab8b7ab56e994d",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
