# coding: utf-8
# Generated by setup.py for PyCBC on 2017-09-01 12:47:44 +0000.

version = '1.7.11'
date = '2017-08-31 15:39:26 +0000'
release = True
last_release = '1.7.11'

git_hash = '5f410fd01e007b99ca7d636837db4698dcbd25c1'
git_branch = 'None'
git_tag = 'v1.7.11'
git_author = 'Steven Reyes <sdreyes@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2017-09-01 12:47:44 +0000'
git_verbose_msg = """Branch: None
Tag: v1.7.11
Id: 5f410fd01e007b99ca7d636837db4698dcbd25c1
Builder: Unknown User <>
Build date: 2017-09-01 12:47:44 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
