from ...tl.tlobject import TLObject


class ContactLinkContact(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    contactLinkContact#d502c2d0 = ContactLink"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xd502c2d0
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xa053c1da

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(ContactLinkContact.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return ContactLinkContact()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'contactLinkContact#d502c2d0 = ContactLink'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
