/* File: _daskrmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Aug  3 15:21:18 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_daskr_error;
static PyObject *_daskr_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_rt_in_daskr__user__routines_typedef)(int *,double *,double *,double *,int *,double *,double *,int *);
typedef void(*cb_psol_in_daskr__user__routines_typedef)(void);
typedef void(*cb_jac_in_daskr__user__routines_typedef)(double *,double *,double *,double *,double *,double *,double *,double *,double *,int *);
typedef void(*cb_res_in_daskr__user__routines_typedef)(double *,double *,double *,double *,double *,int *,double *,int *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"_daskr.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _daskr_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  }
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(_daskr_error,errmess);
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _daskr_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void ddaskr(cb_res_in_daskr__user__routines_typedef,int*,double*,double*,double*,double*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,cb_jac_in_daskr__user__routines_typedef,cb_psol_in_daskr__user__routines_typedef,cb_rt_in_daskr__user__routines_typedef,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************** cb_res_in_daskr__user__routines **********************/
PyObject *cb_res_in_daskr__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_res_in_daskr__user__routines_args_capi = NULL;
int cb_res_in_daskr__user__routines_nofargs = 0;
jmp_buf cb_res_in_daskr__user__routines_jmpbuf;
/*typedef void(*cb_res_in_daskr__user__routines_typedef)(double *,double *,double *,double *,double *,int *,double *,int *);*/
static void cb_res_in_daskr__user__routines (double *t_cb_capi,double *y,double *yprime,double *cj_cb_capi,double *residual,int *ires_cb_capi,double *rpar,int *ipar) {
  PyTupleObject *capi_arglist = cb_res_in_daskr__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  double t=(*t_cb_capi);
  double cj=(*cj_cb_capi);
  int ires=(*ires_cb_capi);
  npy_intp ipar_Dims[1] = {-1};
  npy_intp yprime_Dims[1] = {-1};
  npy_intp residual_Dims[1] = {-1};
  npy_intp y_Dims[1] = {-1};
  npy_intp rpar_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_res_in_daskr__user__routines (maxnofargs=4(-0))\n");
  CFUNCSMESSPY("cb:cb_res_in_daskr__user__routines_capi=",cb_res_in_daskr__user__routines_capi);
  if (cb_res_in_daskr__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_res_in_daskr__user__routines_capi = PyObject_GetAttrString(_daskr_module,"res");
  }
  if (cb_res_in_daskr__user__routines_capi==NULL) {
    PyErr_SetString(_daskr_error,"cb: Callback res not defined (as an argument or module _daskr attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_res_in_daskr__user__routines_capi)) {
  cb_res_in_daskr__user__routines_typedef cb_res_in_daskr__user__routines_cptr;
  cb_res_in_daskr__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_res_in_daskr__user__routines_capi);
  (*cb_res_in_daskr__user__routines_cptr)(t_cb_capi,y,yprime,cj_cb_capi,residual,ires_cb_capi,rpar,ipar);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_daskr_module,"res_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_daskr_error,"Failed to convert _daskr.res_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_daskr_error,"Callback res argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  ipar_Dims[0]=2;
  yprime_Dims[0]=ipar[0];
  residual_Dims[0]=ipar[0];
  y_Dims[0]=ipar[0];
  rpar_Dims[0]=ipar[1];
/*pyobjfrom*/
  if (cb_res_in_daskr__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_res_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,y_Dims,NPY_DOUBLE,NULL,(char*)y,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_res_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,yprime_Dims,NPY_DOUBLE,NULL,(char*)yprime,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_res_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function res.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_res_in_daskr__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,residual_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(residual,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_res_in_daskr__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_res_in_daskr__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_res_in_daskr__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/******************* end of cb_res_in_daskr__user__routines *******************/


/********************** cb_jac_in_daskr__user__routines **********************/
PyObject *cb_jac_in_daskr__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_jac_in_daskr__user__routines_args_capi = NULL;
int cb_jac_in_daskr__user__routines_nofargs = 0;
jmp_buf cb_jac_in_daskr__user__routines_jmpbuf;
/*typedef void(*cb_jac_in_daskr__user__routines_typedef)(double *,double *,double *,double *,double *,double *,double *,double *,double *,int *);*/
static void cb_jac_in_daskr__user__routines (double *t_cb_capi,double *y,double *yprime,double *delta,double *pd,double *cj_cb_capi,double *h_cb_capi,double *wt,double *rpar,int *ipar) {
  PyTupleObject *capi_arglist = cb_jac_in_daskr__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  double t=(*t_cb_capi);
  double cj=(*cj_cb_capi);
  double h=(*h_cb_capi);
  npy_intp ipar_Dims[1] = {-1};
  npy_intp yprime_Dims[1] = {-1};
  npy_intp pd_Dims[2] = {-1, -1};
  npy_intp rpar_Dims[1] = {-1};
  npy_intp wt_Dims[1] = {-1};
  npy_intp delta_Dims[1] = {-1};
  npy_intp y_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_jac_in_daskr__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_jac_in_daskr__user__routines_capi=",cb_jac_in_daskr__user__routines_capi);
  if (cb_jac_in_daskr__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_jac_in_daskr__user__routines_capi = PyObject_GetAttrString(_daskr_module,"jac");
  }
  if (cb_jac_in_daskr__user__routines_capi==NULL) {
    PyErr_SetString(_daskr_error,"cb: Callback jac not defined (as an argument or module _daskr attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_jac_in_daskr__user__routines_capi)) {
  cb_jac_in_daskr__user__routines_typedef cb_jac_in_daskr__user__routines_cptr;
  cb_jac_in_daskr__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_jac_in_daskr__user__routines_capi);
  (*cb_jac_in_daskr__user__routines_cptr)(t_cb_capi,y,yprime,delta,pd,cj_cb_capi,h_cb_capi,wt,rpar,ipar);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_daskr_module,"jac_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_daskr_error,"Failed to convert _daskr.jac_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_daskr_error,"Callback jac argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  ipar_Dims[0]=2;
  yprime_Dims[0]=ipar[0];
  pd_Dims[0]=ipar[0],pd_Dims[1]=ipar[0];
  rpar_Dims[0]=ipar[1];
  wt_Dims[0]=ipar[0];
  delta_Dims[0]=ipar[0];
  y_Dims[0]=ipar[0];
/*pyobjfrom*/
  if (cb_jac_in_daskr__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_jac_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,y_Dims,NPY_DOUBLE,NULL,(char*)y,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_jac_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,yprime_Dims,NPY_DOUBLE,NULL,(char*)yprime,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_jac_in_daskr__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(cj)))
      goto capi_fail;
  if (cb_jac_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function jac.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_jac_in_daskr__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,pd_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(pd,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_jac_in_daskr__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_jac_in_daskr__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_jac_in_daskr__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/******************* end of cb_jac_in_daskr__user__routines *******************/


/********************** cb_psol_in_daskr__user__routines **********************/
PyObject *cb_psol_in_daskr__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_psol_in_daskr__user__routines_args_capi = NULL;
int cb_psol_in_daskr__user__routines_nofargs = 0;
jmp_buf cb_psol_in_daskr__user__routines_jmpbuf;
/*typedef void(*cb_psol_in_daskr__user__routines_typedef)(void);*/
static void cb_psol_in_daskr__user__routines (void) {
  PyTupleObject *capi_arglist = cb_psol_in_daskr__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_psol_in_daskr__user__routines (maxnofargs=0(-0))\n");
  CFUNCSMESSPY("cb:cb_psol_in_daskr__user__routines_capi=",cb_psol_in_daskr__user__routines_capi);
  if (cb_psol_in_daskr__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_psol_in_daskr__user__routines_capi = PyObject_GetAttrString(_daskr_module,"psol");
  }
  if (cb_psol_in_daskr__user__routines_capi==NULL) {
    PyErr_SetString(_daskr_error,"cb: Callback psol not defined (as an argument or module _daskr attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_psol_in_daskr__user__routines_capi)) {
  cb_psol_in_daskr__user__routines_typedef cb_psol_in_daskr__user__routines_cptr;
  cb_psol_in_daskr__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_psol_in_daskr__user__routines_capi);
  (*cb_psol_in_daskr__user__routines_cptr)();
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_daskr_module,"psol_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_daskr_error,"Failed to convert _daskr.psol_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_daskr_error,"Callback psol argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
/*pyobjfrom*/
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function psol.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_psol_in_daskr__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_psol_in_daskr__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_psol_in_daskr__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_psol_in_daskr__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/****************** end of cb_psol_in_daskr__user__routines ******************/


/*********************** cb_rt_in_daskr__user__routines ***********************/
PyObject *cb_rt_in_daskr__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_rt_in_daskr__user__routines_args_capi = NULL;
int cb_rt_in_daskr__user__routines_nofargs = 0;
jmp_buf cb_rt_in_daskr__user__routines_jmpbuf;
/*typedef void(*cb_rt_in_daskr__user__routines_typedef)(int *,double *,double *,double *,int *,double *,double *,int *);*/
static void cb_rt_in_daskr__user__routines (int *neq_cb_capi,double *t_cb_capi,double *y,double *yp,int *nrt_cb_capi,double *r0,double *rpar,int *ipar) {
  PyTupleObject *capi_arglist = cb_rt_in_daskr__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int neq=(*neq_cb_capi);
  double t=(*t_cb_capi);
  int nrt=(*nrt_cb_capi);
  npy_intp ipar_Dims[1] = {-1};
  npy_intp r0_Dims[1] = {-1};
  npy_intp rpar_Dims[1] = {-1};
  npy_intp y_Dims[1] = {-1};
  npy_intp yp_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_rt_in_daskr__user__routines (maxnofargs=4(-0))\n");
  CFUNCSMESSPY("cb:cb_rt_in_daskr__user__routines_capi=",cb_rt_in_daskr__user__routines_capi);
  if (cb_rt_in_daskr__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_rt_in_daskr__user__routines_capi = PyObject_GetAttrString(_daskr_module,"rt");
  }
  if (cb_rt_in_daskr__user__routines_capi==NULL) {
    PyErr_SetString(_daskr_error,"cb: Callback rt not defined (as an argument or module _daskr attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_rt_in_daskr__user__routines_capi)) {
  cb_rt_in_daskr__user__routines_typedef cb_rt_in_daskr__user__routines_cptr;
  cb_rt_in_daskr__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_rt_in_daskr__user__routines_capi);
  (*cb_rt_in_daskr__user__routines_cptr)(neq_cb_capi,t_cb_capi,y,yp,nrt_cb_capi,r0,rpar,ipar);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_daskr_module,"rt_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_daskr_error,"Failed to convert _daskr.rt_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_daskr_error,"Callback rt argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  ipar_Dims[0]=2;
  r0_Dims[0]=nrt;
  rpar_Dims[0]=ipar[1];
  y_Dims[0]=ipar[0];
  yp_Dims[0]=ipar[0];
/*pyobjfrom*/
  if (cb_rt_in_daskr__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_rt_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,y_Dims,NPY_DOUBLE,NULL,(char*)y,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_rt_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,yp_Dims,NPY_DOUBLE,NULL,(char*)yp,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_rt_in_daskr__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function rt.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_rt_in_daskr__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,r0_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(r0,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_rt_in_daskr__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_rt_in_daskr__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_rt_in_daskr__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/******************* end of cb_rt_in_daskr__user__routines *******************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** ddaskr ***********************************/
static char doc_f2py_rout__daskr_ddaskr[] = "\
t,y,yprime,idid,jroot = ddaskr(res,t,y,yprime,tout,info,rtol,atol,rwork,iwork,rpar,ipar,jac,psol,rt,nrt,[res_extra_args,overwrite_y,overwrite_yprime,overwrite_rtol,overwrite_atol,jac_extra_args,psol_extra_args,rt_extra_args])\n\nWrapper for ``ddaskr``.\
\n\nParameters\n----------\n"
"res : call-back function\n"
"t : input float\n"
"y : input rank-1 array('d') with bounds (neq)\n"
"yprime : input rank-1 array('d') with bounds (neq)\n"
"tout : input float\n"
"info : input rank-1 array('i') with bounds (20)\n"
"rtol : input rank-1 array('d') with bounds (neq)\n"
"atol : input rank-1 array('d') with bounds (neq)\n"
"rwork : input rank-1 array('d') with bounds (lrw)\n"
"iwork : input rank-1 array('i') with bounds (liw)\n"
"rpar : input rank-1 array('d') with bounds (ipar[1])\n"
"ipar : input rank-1 array('i') with bounds (2)\n"
"jac : call-back function\n"
"psol : call-back function\n"
"rt : call-back function\n"
"nrt : input int\n"
"\nOther Parameters\n----------------\n"
"res_extra_args : input tuple, optional\n    Default: ()\n"
"overwrite_y : input int, optional\n    Default: 0\n"
"overwrite_yprime : input int, optional\n    Default: 0\n"
"overwrite_rtol : input int, optional\n    Default: 0\n"
"overwrite_atol : input int, optional\n    Default: 0\n"
"jac_extra_args : input tuple, optional\n    Default: ()\n"
"psol_extra_args : input tuple, optional\n    Default: ()\n"
"rt_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"t : float\n"
"y : rank-1 array('d') with bounds (neq)\n"
"yprime : rank-1 array('d') with bounds (neq)\n"
"idid : int\n"
"jroot : rank-1 array('i') with bounds (MAX(1, nrt))\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def res(t,y,yprime,rpar): return residual\n\
  Required arguments:\n"
"    t : input float\n"
"    y : input rank-1 array('d') with bounds (ipar[0])\n"
"    yprime : input rank-1 array('d') with bounds (ipar[0])\n"
"    rpar : input rank-1 array('d') with bounds (ipar[1])\n"
"  Return objects:\n"
"    residual : rank-1 array('d') with bounds (ipar[0])\n"
"  def jac(t,y,yprime,cj,rpar): return pd\n\
  Required arguments:\n"
"    t : input float\n"
"    y : input rank-1 array('d') with bounds (ipar[0])\n"
"    yprime : input rank-1 array('d') with bounds (ipar[0])\n"
"    cj : input float\n"
"    rpar : input rank-1 array('d') with bounds (ipar[1])\n"
"  Return objects:\n"
"    pd : rank-2 array('d') with bounds (ipar[0],ipar[0])\n"
"  def psol(): return \n\
\n"
"  def rt(t,y,yp,rpar): return r0\n\
  Required arguments:\n"
"    t : input float\n"
"    y : input rank-1 array('d') with bounds (ipar[0])\n"
"    yp : input rank-1 array('d') with bounds (ipar[0])\n"
"    rpar : input rank-1 array('d') with bounds (ipar[1])\n"
"  Return objects:\n"
"    r0 : rank-1 array('d') with bounds (nrt)";
/* extern void ddaskr(cb_res_in_daskr__user__routines_typedef,int*,double*,double*,double*,double*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,cb_jac_in_daskr__user__routines_typedef,cb_psol_in_daskr__user__routines_typedef,cb_rt_in_daskr__user__routines_typedef,int*,int*); */
static PyObject *f2py_rout__daskr_ddaskr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(cb_res_in_daskr__user__routines_typedef,int*,double*,double*,double*,double*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,cb_jac_in_daskr__user__routines_typedef,cb_psol_in_daskr__user__routines_typedef,cb_rt_in_daskr__user__routines_typedef,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  PyObject *res_capi = Py_None;
  PyTupleObject *res_xa_capi = NULL;
  PyTupleObject *res_args_capi = NULL;
  int res_nofargs_capi = 0;
  cb_res_in_daskr__user__routines_typedef res_cptr;
  int neq = 0;
  double t = 0;
  PyObject *t_capi = Py_None;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  int capi_overwrite_y = 0;
  PyObject *y_capi = Py_None;
  double *yprime = NULL;
  npy_intp yprime_Dims[1] = {-1};
  const int yprime_Rank = 1;
  PyArrayObject *capi_yprime_tmp = NULL;
  int capi_yprime_intent = 0;
  int capi_overwrite_yprime = 0;
  PyObject *yprime_capi = Py_None;
  double tout = 0;
  PyObject *tout_capi = Py_None;
  int *info = NULL;
  npy_intp info_Dims[1] = {-1};
  const int info_Rank = 1;
  PyArrayObject *capi_info_tmp = NULL;
  int capi_info_intent = 0;
  PyObject *info_capi = Py_None;
  double *rtol = NULL;
  npy_intp rtol_Dims[1] = {-1};
  const int rtol_Rank = 1;
  PyArrayObject *capi_rtol_tmp = NULL;
  int capi_rtol_intent = 0;
  int capi_overwrite_rtol = 0;
  PyObject *rtol_capi = Py_None;
  double *atol = NULL;
  npy_intp atol_Dims[1] = {-1};
  const int atol_Rank = 1;
  PyArrayObject *capi_atol_tmp = NULL;
  int capi_atol_intent = 0;
  int capi_overwrite_atol = 0;
  PyObject *atol_capi = Py_None;
  int idid = 0;
  double *rwork = NULL;
  npy_intp rwork_Dims[1] = {-1};
  const int rwork_Rank = 1;
  PyArrayObject *capi_rwork_tmp = NULL;
  int capi_rwork_intent = 0;
  PyObject *rwork_capi = Py_None;
  int lrw = 0;
  int *iwork = NULL;
  npy_intp iwork_Dims[1] = {-1};
  const int iwork_Rank = 1;
  PyArrayObject *capi_iwork_tmp = NULL;
  int capi_iwork_intent = 0;
  PyObject *iwork_capi = Py_None;
  int liw = 0;
  double *rpar = NULL;
  npy_intp rpar_Dims[1] = {-1};
  const int rpar_Rank = 1;
  PyArrayObject *capi_rpar_tmp = NULL;
  int capi_rpar_intent = 0;
  PyObject *rpar_capi = Py_None;
  int *ipar = NULL;
  npy_intp ipar_Dims[1] = {-1};
  const int ipar_Rank = 1;
  PyArrayObject *capi_ipar_tmp = NULL;
  int capi_ipar_intent = 0;
  PyObject *ipar_capi = Py_None;
  PyObject *jac_capi = Py_None;
  PyTupleObject *jac_xa_capi = NULL;
  PyTupleObject *jac_args_capi = NULL;
  int jac_nofargs_capi = 0;
  cb_jac_in_daskr__user__routines_typedef jac_cptr;
  PyObject *psol_capi = Py_None;
  PyTupleObject *psol_xa_capi = NULL;
  PyTupleObject *psol_args_capi = NULL;
  int psol_nofargs_capi = 0;
  cb_psol_in_daskr__user__routines_typedef psol_cptr;
  PyObject *rt_capi = Py_None;
  PyTupleObject *rt_xa_capi = NULL;
  PyTupleObject *rt_args_capi = NULL;
  int rt_nofargs_capi = 0;
  cb_rt_in_daskr__user__routines_typedef rt_cptr;
  int nrt = 0;
  PyObject *nrt_capi = Py_None;
  int *jroot = NULL;
  npy_intp jroot_Dims[1] = {-1};
  const int jroot_Rank = 1;
  PyArrayObject *capi_jroot_tmp = NULL;
  int capi_jroot_intent = 0;
  static char *capi_kwlist[] = {"res","t","y","yprime","tout","info","rtol","atol","rwork","iwork","rpar","ipar","jac","psol","rt","nrt","res_extra_args","overwrite_y","overwrite_yprime","overwrite_rtol","overwrite_atol","jac_extra_args","psol_extra_args","rt_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|O!iiiiO!O!O!:_daskr.ddaskr",\
    capi_kwlist,&res_capi,&t_capi,&y_capi,&yprime_capi,&tout_capi,&info_capi,&rtol_capi,&atol_capi,&rwork_capi,&iwork_capi,&rpar_capi,&ipar_capi,&jac_capi,&psol_capi,&rt_capi,&nrt_capi,&PyTuple_Type,&res_xa_capi,&capi_overwrite_y,&capi_overwrite_yprime,&capi_overwrite_rtol,&capi_overwrite_atol,&PyTuple_Type,&jac_xa_capi,&PyTuple_Type,&psol_xa_capi,&PyTuple_Type,&rt_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iwork */
  ;
  capi_iwork_intent |= F2PY_INTENT_IN;
  capi_iwork_tmp = array_from_pyobj(NPY_INT,iwork_Dims,iwork_Rank,capi_iwork_intent,iwork_capi);
  if (capi_iwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 10th argument `iwork' of _daskr.ddaskr to C/Fortran array" );
  } else {
    iwork = (int *)(PyArray_DATA(capi_iwork_tmp));

  /* Processing variable nrt */
    f2py_success = int_from_pyobj(&nrt,nrt_capi,"_daskr.ddaskr() 16th argument (nrt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable rt */
if(F2PyCapsule_Check(rt_capi)) {
  rt_cptr = F2PyCapsule_AsVoidPtr(rt_capi);
} else {
  rt_cptr = cb_rt_in_daskr__user__routines;
}

  rt_nofargs_capi = cb_rt_in_daskr__user__routines_nofargs;
  if (create_cb_arglist(rt_capi,rt_xa_capi,4,0,&cb_rt_in_daskr__user__routines_nofargs,&rt_args_capi,"failed in processing argument list for call-back rt.")) {
    jmp_buf rt_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `rt`.\n");
    SWAP(rt_capi,cb_rt_in_daskr__user__routines_capi,PyObject);
    SWAP(rt_args_capi,cb_rt_in_daskr__user__routines_args_capi,PyTupleObject);
    memcpy(&rt_jmpbuf,&cb_rt_in_daskr__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable info */
  info_Dims[0]=20;
  capi_info_intent |= F2PY_INTENT_IN;
  capi_info_tmp = array_from_pyobj(NPY_INT,info_Dims,info_Rank,capi_info_intent,info_capi);
  if (capi_info_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 6th argument `info' of _daskr.ddaskr to C/Fortran array" );
  } else {
    info = (int *)(PyArray_DATA(capi_info_tmp));

  /* Processing variable res */
if(F2PyCapsule_Check(res_capi)) {
  res_cptr = F2PyCapsule_AsVoidPtr(res_capi);
} else {
  res_cptr = cb_res_in_daskr__user__routines;
}

  res_nofargs_capi = cb_res_in_daskr__user__routines_nofargs;
  if (create_cb_arglist(res_capi,res_xa_capi,4,0,&cb_res_in_daskr__user__routines_nofargs,&res_args_capi,"failed in processing argument list for call-back res.")) {
    jmp_buf res_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `res`.\n");
    SWAP(res_capi,cb_res_in_daskr__user__routines_capi,PyObject);
    SWAP(res_args_capi,cb_res_in_daskr__user__routines_args_capi,PyTupleObject);
    memcpy(&res_jmpbuf,&cb_res_in_daskr__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable rwork */
  ;
  capi_rwork_intent |= F2PY_INTENT_IN;
  capi_rwork_tmp = array_from_pyobj(NPY_DOUBLE,rwork_Dims,rwork_Rank,capi_rwork_intent,rwork_capi);
  if (capi_rwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 9th argument `rwork' of _daskr.ddaskr to C/Fortran array" );
  } else {
    rwork = (double *)(PyArray_DATA(capi_rwork_tmp));

  /* Processing variable tout */
    f2py_success = double_from_pyobj(&tout,tout_capi,"_daskr.ddaskr() 5th argument (tout) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"_daskr.ddaskr() 2nd argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ipar */
  ipar_Dims[0]=2;
  capi_ipar_intent |= F2PY_INTENT_IN;
  capi_ipar_tmp = array_from_pyobj(NPY_INT,ipar_Dims,ipar_Rank,capi_ipar_intent,ipar_capi);
  if (capi_ipar_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 12nd argument `ipar' of _daskr.ddaskr to C/Fortran array" );
  } else {
    ipar = (int *)(PyArray_DATA(capi_ipar_tmp));

  /* Processing variable y */
  capi_y_intent |= (capi_overwrite_y?0:F2PY_INTENT_COPY);
  ;
  capi_y_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 3rd argument `y' of _daskr.ddaskr to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable psol */
if(F2PyCapsule_Check(psol_capi)) {
  psol_cptr = F2PyCapsule_AsVoidPtr(psol_capi);
} else {
  psol_cptr = cb_psol_in_daskr__user__routines;
}

  psol_nofargs_capi = cb_psol_in_daskr__user__routines_nofargs;
  if (create_cb_arglist(psol_capi,psol_xa_capi,0,0,&cb_psol_in_daskr__user__routines_nofargs,&psol_args_capi,"failed in processing argument list for call-back psol.")) {
    jmp_buf psol_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `psol`.\n");
    SWAP(psol_capi,cb_psol_in_daskr__user__routines_capi,PyObject);
    SWAP(psol_args_capi,cb_psol_in_daskr__user__routines_args_capi,PyTupleObject);
    memcpy(&psol_jmpbuf,&cb_psol_in_daskr__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable idid */
  /* Processing variable jac */
if(F2PyCapsule_Check(jac_capi)) {
  jac_cptr = F2PyCapsule_AsVoidPtr(jac_capi);
} else {
  jac_cptr = cb_jac_in_daskr__user__routines;
}

  jac_nofargs_capi = cb_jac_in_daskr__user__routines_nofargs;
  if (create_cb_arglist(jac_capi,jac_xa_capi,5,0,&cb_jac_in_daskr__user__routines_nofargs,&jac_args_capi,"failed in processing argument list for call-back jac.")) {
    jmp_buf jac_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `jac`.\n");
    SWAP(jac_capi,cb_jac_in_daskr__user__routines_capi,PyObject);
    SWAP(jac_args_capi,cb_jac_in_daskr__user__routines_args_capi,PyTupleObject);
    memcpy(&jac_jmpbuf,&cb_jac_in_daskr__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable lrw */
  lrw = len(rwork);
  /* Processing variable rpar */
  rpar_Dims[0]=ipar[1];
  capi_rpar_intent |= F2PY_INTENT_IN;
  capi_rpar_tmp = array_from_pyobj(NPY_DOUBLE,rpar_Dims,rpar_Rank,capi_rpar_intent,rpar_capi);
  if (capi_rpar_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 11st argument `rpar' of _daskr.ddaskr to C/Fortran array" );
  } else {
    rpar = (double *)(PyArray_DATA(capi_rpar_tmp));

  /* Processing variable jroot */
  jroot_Dims[0]=MAX(1, nrt);
  capi_jroot_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_jroot_tmp = array_from_pyobj(NPY_INT,jroot_Dims,jroot_Rank,capi_jroot_intent,Py_None);
  if (capi_jroot_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting hidden `jroot' of _daskr.ddaskr to C/Fortran array" );
  } else {
    jroot = (int *)(PyArray_DATA(capi_jroot_tmp));

  /* Processing variable liw */
  liw = len(iwork);
  /* Processing variable neq */
  neq = len(y);
  /* Processing variable rtol */
  capi_rtol_intent |= (capi_overwrite_rtol?0:F2PY_INTENT_COPY);
  rtol_Dims[0]=neq;
  capi_rtol_intent |= F2PY_INTENT_IN;
  capi_rtol_tmp = array_from_pyobj(NPY_DOUBLE,rtol_Dims,rtol_Rank,capi_rtol_intent,rtol_capi);
  if (capi_rtol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 7th argument `rtol' of _daskr.ddaskr to C/Fortran array" );
  } else {
    rtol = (double *)(PyArray_DATA(capi_rtol_tmp));

  /* Processing variable atol */
  capi_atol_intent |= (capi_overwrite_atol?0:F2PY_INTENT_COPY);
  atol_Dims[0]=neq;
  capi_atol_intent |= F2PY_INTENT_IN;
  capi_atol_tmp = array_from_pyobj(NPY_DOUBLE,atol_Dims,atol_Rank,capi_atol_intent,atol_capi);
  if (capi_atol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 8th argument `atol' of _daskr.ddaskr to C/Fortran array" );
  } else {
    atol = (double *)(PyArray_DATA(capi_atol_tmp));

  /* Processing variable yprime */
  capi_yprime_intent |= (capi_overwrite_yprime?0:F2PY_INTENT_COPY);
  yprime_Dims[0]=neq;
  capi_yprime_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_yprime_tmp = array_from_pyobj(NPY_DOUBLE,yprime_Dims,yprime_Rank,capi_yprime_intent,yprime_capi);
  if (capi_yprime_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_daskr_error,"failed in converting 4th argument `yprime' of _daskr.ddaskr to C/Fortran array" );
  } else {
    yprime = (double *)(PyArray_DATA(capi_yprime_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_res_in_daskr__user__routines_jmpbuf)) || (setjmp(cb_jac_in_daskr__user__routines_jmpbuf)) || (setjmp(cb_psol_in_daskr__user__routines_jmpbuf)) || (setjmp(cb_rt_in_daskr__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(res_cptr,&neq,&t,y,yprime,&tout,info,rtol,atol,&idid,rwork,&lrw,iwork,&liw,rpar,ipar,jac_cptr,psol_cptr,rt_cptr,&nrt,jroot);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("dNNiN",t,capi_y_tmp,capi_yprime_tmp,idid,capi_jroot_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_yprime_tmp == NULL) ... else of yprime*/
  /* End of cleaning variable yprime */
  if((PyObject *)capi_atol_tmp!=atol_capi) {
    Py_XDECREF(capi_atol_tmp); }
  }  /*if (capi_atol_tmp == NULL) ... else of atol*/
  /* End of cleaning variable atol */
  if((PyObject *)capi_rtol_tmp!=rtol_capi) {
    Py_XDECREF(capi_rtol_tmp); }
  }  /*if (capi_rtol_tmp == NULL) ... else of rtol*/
  /* End of cleaning variable rtol */
  /* End of cleaning variable neq */
  /* End of cleaning variable liw */
  }  /*if (capi_jroot_tmp == NULL) ... else of jroot*/
  /* End of cleaning variable jroot */
  if((PyObject *)capi_rpar_tmp!=rpar_capi) {
    Py_XDECREF(capi_rpar_tmp); }
  }  /*if (capi_rpar_tmp == NULL) ... else of rpar*/
  /* End of cleaning variable rpar */
  /* End of cleaning variable lrw */
    CFUNCSMESS("Restoring jmpbuf for `jac`.\n");
    cb_jac_in_daskr__user__routines_capi = jac_capi;
    Py_DECREF(cb_jac_in_daskr__user__routines_args_capi);
    cb_jac_in_daskr__user__routines_args_capi = jac_args_capi;
    cb_jac_in_daskr__user__routines_nofargs = jac_nofargs_capi;
    memcpy(&cb_jac_in_daskr__user__routines_jmpbuf,&jac_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable jac */
  /* End of cleaning variable idid */
    CFUNCSMESS("Restoring jmpbuf for `psol`.\n");
    cb_psol_in_daskr__user__routines_capi = psol_capi;
    Py_DECREF(cb_psol_in_daskr__user__routines_args_capi);
    cb_psol_in_daskr__user__routines_args_capi = psol_args_capi;
    cb_psol_in_daskr__user__routines_nofargs = psol_nofargs_capi;
    memcpy(&cb_psol_in_daskr__user__routines_jmpbuf,&psol_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable psol */
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_ipar_tmp!=ipar_capi) {
    Py_XDECREF(capi_ipar_tmp); }
  }  /*if (capi_ipar_tmp == NULL) ... else of ipar*/
  /* End of cleaning variable ipar */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  } /*if (f2py_success) of tout*/
  /* End of cleaning variable tout */
  if((PyObject *)capi_rwork_tmp!=rwork_capi) {
    Py_XDECREF(capi_rwork_tmp); }
  }  /*if (capi_rwork_tmp == NULL) ... else of rwork*/
  /* End of cleaning variable rwork */
    CFUNCSMESS("Restoring jmpbuf for `res`.\n");
    cb_res_in_daskr__user__routines_capi = res_capi;
    Py_DECREF(cb_res_in_daskr__user__routines_args_capi);
    cb_res_in_daskr__user__routines_args_capi = res_args_capi;
    cb_res_in_daskr__user__routines_nofargs = res_nofargs_capi;
    memcpy(&cb_res_in_daskr__user__routines_jmpbuf,&res_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable res */
  if((PyObject *)capi_info_tmp!=info_capi) {
    Py_XDECREF(capi_info_tmp); }
  }  /*if (capi_info_tmp == NULL) ... else of info*/
  /* End of cleaning variable info */
    CFUNCSMESS("Restoring jmpbuf for `rt`.\n");
    cb_rt_in_daskr__user__routines_capi = rt_capi;
    Py_DECREF(cb_rt_in_daskr__user__routines_args_capi);
    cb_rt_in_daskr__user__routines_args_capi = rt_args_capi;
    cb_rt_in_daskr__user__routines_nofargs = rt_nofargs_capi;
    memcpy(&cb_rt_in_daskr__user__routines_jmpbuf,&rt_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable rt */
  } /*if (f2py_success) of nrt*/
  /* End of cleaning variable nrt */
  if((PyObject *)capi_iwork_tmp!=iwork_capi) {
    Py_XDECREF(capi_iwork_tmp); }
  }  /*if (capi_iwork_tmp == NULL) ... else of iwork*/
  /* End of cleaning variable iwork */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ddaskr *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ddaskr",-1,{{-1}},0,(char *)ddaskr,(f2py_init_func)f2py_rout__daskr_ddaskr,doc_f2py_rout__daskr_ddaskr},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_daskr",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__daskr(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_daskr(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _daskr_module = PyModule_Create(&moduledef);
#else
  m = _daskr_module = Py_InitModule("_daskr", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _daskr (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_daskr' is auto-generated with f2py (version:2).\nFunctions:\n"
"  t,y,yprime,idid,jroot = ddaskr(res,t,y,yprime,tout,info,rtol,atol,rwork,iwork,rpar,ipar,jac,psol,rt,nrt,res_extra_args=(),overwrite_y=0,overwrite_yprime=0,overwrite_rtol=0,overwrite_atol=0,jac_extra_args=(),psol_extra_args=(),rt_extra_args=())\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _daskr_error = PyErr_NewException ("_daskr.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_daskr");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
