site_name: Git Lazy
site_author: Tim Santor
site_description: Does bulk status|push|pull operations on git repos.
copyright: Tim Santor

repo_url: https://bitbucket.org/tsantor/git-lazy/
repo_name: Bitbucket

# Put a favicon.ico into the docs/ directory
#site_favicon: favicon.ico

# pages:
# - Home: 'index.md'
# - User Guide:
#     - 'Writing your docs': 'user-guide/writing-your-docs.md'
#     - 'Styling your docs': 'user-guide/styling-your-docs.md'
# - About:
#     - 'License': 'about/license.md'
#     - 'Release Notes': 'about/release-notes.md'

#google_analytics: ['UA-36723568-3', 'mkdocs.org']

#theme: readthedocs
