# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import unach_photo_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('unach_photo_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appregister',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appregister',
            name='token',
            field=models.CharField(default=unach_photo_server.models.generate_hash, max_length=40, unique=True),
        ),
    ]
