# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unach_photo_server', '0006_photorepository_is_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorepository',
            name='database_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
