name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- sphinx=1.4.8
- python=3.5
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- ipywidgets
- notebook>=4.2
- sphinx>=1.4.6
- ipykernel
- pip:
  - docutils<0.13.1
  - jupyter_sphinx
  - git+https://github.com/spatialaudio/nbsphinx.git#egg=nbsphinx
  - sphinx_rtd_theme==0.1.10-alpha
  - python-dateutil
  - recommonmark==0.4.0
