
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-29T13:15:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "49b537b771157f159eb040048bb51b6a69138604",
 "version": "1.0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
