document: meta-test
version: 1
name: baseruntime
modulemd-url: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/plain/base-runtime.yaml
packages:
    profiles:
        - baseimage
default_module: docker
module:
    docker:
        container: docker=base-runtime-smoke
    rpm:
        repos:
            - https://kojipkgs.stg.fedoraproject.org/compose/branched/jkaluza/latest-Boltron-26/compose/base-runtime/x86_64/os/
