heat_template_version: pike

resources:

  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: setup_docker_host}

  setup_docker_host:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: ./setup_docker_host.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
