# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unach_photo_server', '0003_photorepository_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorepository',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photorepository',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
