image: python:2.7

variables:
  VCD_PASS: $VCD_PASSWORD

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - pip install -r test-requirements.txt
    - tox -e flake8
    - pip install .
    - nosetests tests/00010_vcd_login.py --tc-format yaml --tc-file tests/config.yaml --tc=vcloud.host:$VCD_HOST --tc=vcloud.username:$VCD_USERNAME --tc=vcloud.password:$VCD_PASS

deploy:
  stage: deploy
  script:
    - ./.upload-to-pip.sh
  dependencies:
    - unit_test
