
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "511d17e0b0099f65630969ad915c333833d46299",
 "version": "0.1.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
