
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b0c3e705b936a0aaf41bc612c5971669c6354744",
 "version": "0.6.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
