heat_template_version: pike

description: >
  OpenStack Nova API service configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaWorkers:
    default: 0
    description: Number of workers for Nova services.
    type: number

conditions:
  nova_workers_zero: {equals : [{get_param: NovaWorkers}, 0]}

outputs:
  role_data:
    description: Role data for the Nova Metadata service.
    value:
      service_name: nova_metadata
      config_settings:
        map_merge:
        - nova::api::metadata_listen: {get_param: [ServiceNetMap, NovaMetadataNetwork]}
        -
          if:
          - nova_workers_zero
          - {}
          - nova::api::metadata_workers: {get_param: NovaWorkers}
      step_config: ""
