# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0004_auto_20170712_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='simc',
            name='terc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna'),
        ),
    ]
