#######################################################################
#
# VidCutter - media cutter & joiner
#
# copyright © 2017 Pete Alexandrou
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################

language: python
os: linux
dist: trusty
group: edge
sudo: required
python: '3.5'
git:
  depth: 3
branches:
  only:
  - master
  - /^feature\/.*$/

before_install:
  - sudo add-apt-repository ppa:mc3man/testing6 -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libmpv-dev libmpv1 python3-dev python3-setuptools

install:
  - sed -i "s/pypi/deb/" "vidcutter/__init__.py"
  - python setup.py build_ext -i
  - sudo pip install .

script: echo "Done!"

notifications:
  email: false
