# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WScan(object):
    def setupUi(self, WScan):
        WScan.setObjectName("WScan")
        WScan.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WScan)
        self.centralwidget.setObjectName("centralwidget")
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(430, 80, 256, 192))
        self.plot.setObjectName("plot")
        self.controlsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlsGroupBox.setGeometry(QtCore.QRect(40, 50, 266, 421))
        self.controlsGroupBox.setObjectName("controlsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.currentPositionLabel = QtWidgets.QLabel(self.controlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.currentPositionLabel.setFont(font)
        self.currentPositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPositionLabel.setObjectName("currentPositionLabel")
        self.horizontalLayout_17.addWidget(self.currentPositionLabel)
        self.axisComboBox = QtWidgets.QComboBox(self.controlsGroupBox)
        self.axisComboBox.setEditable(True)
        self.axisComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.axisComboBox.setObjectName("axisComboBox")
        self.axisComboBox.addItem("")
        self.horizontalLayout_17.addWidget(self.axisComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.fromSpinBox = QtWidgets.QDoubleSpinBox(self.controlsGroupBox)
        self.fromSpinBox.setDecimals(5)
        self.fromSpinBox.setMinimum(-100000.0)
        self.fromSpinBox.setMaximum(100000.0)
        self.fromSpinBox.setObjectName("fromSpinBox")
        self.horizontalLayout_15.addWidget(self.fromSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.toSpinBox = QtWidgets.QDoubleSpinBox(self.controlsGroupBox)
        self.toSpinBox.setDecimals(5)
        self.toSpinBox.setMinimum(-100000.0)
        self.toSpinBox.setMaximum(100000.0)
        self.toSpinBox.setObjectName("toSpinBox")
        self.horizontalLayout_20.addWidget(self.toSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.stepSpinBox = QtWidgets.QDoubleSpinBox(self.controlsGroupBox)
        self.stepSpinBox.setDecimals(5)
        self.stepSpinBox.setMinimum(-100000.0)
        self.stepSpinBox.setMaximum(100000.0)
        self.stepSpinBox.setObjectName("stepSpinBox")
        self.horizontalLayout_19.addWidget(self.stepSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.exposureSpinBox = QtWidgets.QDoubleSpinBox(self.controlsGroupBox)
        self.exposureSpinBox.setDecimals(3)
        self.exposureSpinBox.setMinimum(-100000.0)
        self.exposureSpinBox.setMaximum(100000.0)
        self.exposureSpinBox.setObjectName("exposureSpinBox")
        self.horizontalLayout_16.addWidget(self.exposureSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.controlsGroupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.filterSpinBox = QtWidgets.QSpinBox(self.controlsGroupBox)
        self.filterSpinBox.setMaximum(10)
        self.filterSpinBox.setObjectName("filterSpinBox")
        self.horizontalLayout_22.addWidget(self.filterSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.rootButton = QtWidgets.QPushButton(self.controlsGroupBox)
        self.rootButton.setObjectName("rootButton")
        self.horizontalLayout_18.addWidget(self.rootButton)
        self.shotButton = QtWidgets.QPushButton(self.controlsGroupBox)
        self.shotButton.setObjectName("shotButton")
        self.horizontalLayout_18.addWidget(self.shotButton)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.startButton = QtWidgets.QPushButton(self.controlsGroupBox)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_21.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.controlsGroupBox)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_21.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentPositionLabel_2 = QtWidgets.QLabel(self.controlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.currentPositionLabel_2.setFont(font)
        self.currentPositionLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPositionLabel_2.setObjectName("currentPositionLabel_2")
        self.horizontalLayout.addWidget(self.currentPositionLabel_2)
        self.xposLabel = QtWidgets.QLabel(self.controlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.xposLabel.setFont(font)
        self.xposLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xposLabel.setObjectName("xposLabel")
        self.horizontalLayout.addWidget(self.xposLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currentPositionLabel_4 = QtWidgets.QLabel(self.controlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.currentPositionLabel_4.setFont(font)
        self.currentPositionLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPositionLabel_4.setObjectName("currentPositionLabel_4")
        self.horizontalLayout_2.addWidget(self.currentPositionLabel_4)
        self.yposLabel = QtWidgets.QLabel(self.controlsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.yposLabel.setFont(font)
        self.yposLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yposLabel.setObjectName("yposLabel")
        self.horizontalLayout_2.addWidget(self.yposLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        WScan.setCentralWidget(self.centralwidget)

        self.retranslateUi(WScan)
        self.axisComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(WScan)

    def retranslateUi(self, WScan):
        _translate = QtCore.QCoreApplication.translate
        WScan.setWindowTitle(_translate("WScan", "General Scan"))
        self.controlsGroupBox.setTitle(_translate("WScan", "Scan control"))
        self.label_13.setText(_translate("WScan", "Axis"))
        self.currentPositionLabel.setText(_translate("WScan", "000000"))
        self.axisComboBox.setItemText(0, _translate("WScan", "pldistd"))
        self.label_11.setText(_translate("WScan", "From"))
        self.label_15.setText(_translate("WScan", "To"))
        self.label_14.setText(_translate("WScan", "Step"))
        self.label_12.setText(_translate("WScan", "Exposure"))
        self.label_16.setText(_translate("WScan", "Filter"))
        self.rootButton.setText(_translate("WScan", "Root"))
        self.shotButton.setText(_translate("WScan", "Shot"))
        self.startButton.setText(_translate("WScan", "Start"))
        self.stopButton.setText(_translate("WScan", "Stop"))
        self.currentPositionLabel_2.setText(_translate("WScan", "X:"))
        self.xposLabel.setText(_translate("WScan", "000000"))
        self.currentPositionLabel_4.setText(_translate("WScan", "Y:"))
        self.yposLabel.setText(_translate("WScan", "000000"))

from pyqtgraph import PlotWidget

