
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3a50d4004544f1931a658a4eb1d2d09ccb6c4eb3",
 "version": "1.0.0.post.dev656"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
