#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wasmfun']

package_data = \
{'': ['*']}

setup(name='wasmfun',
      version='0.1',
      description='A Python library that provides tools to handle WASM code.',
      author='Almar Klein',
      author_email='almar.klein@gmail.com',
      url='https://github.com/almarklein/wasmfun',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.4',
     )
