
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f2d9dc6b826f936bb90707871b35a528e4eaed04",
 "version": "0.7.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
