# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_lessons', '0002_auto_20170518_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprivatelessondetails',
            name='couples',
            field=models.BooleanField(default=True, verbose_name='Private lessons for couples'),
        ),
        migrations.AddField(
            model_name='instructorprivatelessondetails',
            name='smallGroups',
            field=models.BooleanField(default=True, verbose_name='Private lessons for small groups'),
        ),
    ]
