# coding: utf-8

"""
    Swaggy Jenkins

    Jenkins API clients generated from Swagger / Open API specification

    OpenAPI spec version: 0.1.0
    Contact: blah@cliffano.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swaggyjenkins
from swaggyjenkins.rest import ApiException
from swaggyjenkins.apis.blue_ocean_api import BlueOceanApi


class TestBlueOceanApi(unittest.TestCase):
    """ BlueOceanApi unit test stubs """

    def setUp(self):
        self.api = swaggyjenkins.apis.blue_ocean_api.BlueOceanApi()

    def tearDown(self):
        pass

    def test_get_authenticated_user(self):
        """
        Test case for get_authenticated_user

        
        """
        pass

    def test_get_classes(self):
        """
        Test case for get_classes

        
        """
        pass

    def test_get_organisation(self):
        """
        Test case for get_organisation

        
        """
        pass

    def test_get_organisations(self):
        """
        Test case for get_organisations

        
        """
        pass

    def test_get_pipeline_branch_by_org(self):
        """
        Test case for get_pipeline_branch_by_org

        
        """
        pass

    def test_get_pipeline_branches_by_org(self):
        """
        Test case for get_pipeline_branches_by_org

        
        """
        pass

    def test_get_pipeline_by_org(self):
        """
        Test case for get_pipeline_by_org

        
        """
        pass

    def test_get_pipeline_folder_by_org(self):
        """
        Test case for get_pipeline_folder_by_org

        
        """
        pass

    def test_get_pipeline_folder_by_org_0(self):
        """
        Test case for get_pipeline_folder_by_org_0

        
        """
        pass

    def test_get_pipelines_by_org(self):
        """
        Test case for get_pipelines_by_org

        
        """
        pass

    def test_get_user(self):
        """
        Test case for get_user

        
        """
        pass

    def test_get_users(self):
        """
        Test case for get_users

        
        """
        pass

    def test_search(self):
        """
        Test case for search

        
        """
        pass

    def test_search_0(self):
        """
        Test case for search_0

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
