# coding: utf-8

"""
    Swaggy Jenkins

    Jenkins API clients generated from Swagger / Open API specification

    OpenAPI spec version: 0.1.0
    Contact: blah@cliffano.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swaggyjenkins
from swaggyjenkins.rest import ApiException
from swaggyjenkins.models.get_pipeline_branchesitem_pull_request import GetPipelineBranchesitemPullRequest


class TestGetPipelineBranchesitemPullRequest(unittest.TestCase):
    """ GetPipelineBranchesitemPullRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPipelineBranchesitemPullRequest(self):
        """
        Test GetPipelineBranchesitemPullRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swaggyjenkins.models.get_pipeline_branchesitem_pull_request.GetPipelineBranchesitemPullRequest()
        pass


if __name__ == '__main__':
    unittest.main()
