from ...tl.tlobject import TLObject


class InputMediaEmpty(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputMediaEmpty#9664f57f = InputMedia"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x9664f57f
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xfaf846f4

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputMediaEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputMediaEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMediaEmpty#9664f57f = InputMedia'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
