
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.6'
version_full = '62f9a274f870d19e67e7d9f9a3670a86cc407841'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

