= Subconvert next changelog

== Changes since 2.1.0:

=== Incompatible changes

* Move Subconvert build and installation to setuptools and tox.
+
Autotools build system is now removed. Thanks to this, after few years,
Subconvert is brought back to PYPI (but under a new link).

* [CLI] When `-o --output-file` option is not passed, Subconvert prints
  converted subtitles to stdout.

* [CLI] Removed previously deprecated `-A --auto-fps` option.

* Dropped mplayer dependency.
+
It's replaced with libmediainfo+pymediainfo and video playback provided by
libmpv.

* Subconvert won't change file format when not asked.
+
Previously it changed it automatically to SubRip in CLI mode without `-t`
option, kept it in GUI mode and changed it to the first from list in Property
File Editor.

=== New features

* Added subtitle synchronization and offsetting.
+
Subtitles can be now synchronized to selected time points in a movie, or can be
offsetted, i.e. changed by some fixed value.

* Times with negative values can be displayed. They can't be saved though.

* Side panel's view is tabbed.

* Added a backward frame-by-frame video playback (mapped to `,` (colon)).

* Added a possibility to disable changing output format in Property Files.

=== Bug fixes

* Fixed incorrect slot definition which prevented starting Subconvert in GUI
  mode.

* Fixed a crash when sending any command to MPlayer process.
+
Strings are no longer accepted, only encoded byte steams.

* Fixed not changing framerate of particular subtitles when detecting it from
  linked videos.

* Fixed adding/removing/modifying subtitles for all opened tabs.

* Fixed occasional (but deterministic) problem with incorrect rounding of
  milliseconds in subtitle times to 1000.

* Subconvert will now correctly handle signals (SIGINT and SIGTERM) and
  when such signal is sent it'll clean up resources and exit with a correct exit
  code.
+
For details on why it's important, see:
https://www.cons.org/cracauer/sigint.html

* Subconvert will keep auto-detected encoding for output files when Property
  File has auto-detection set together with a different input encoding.

=== Removed functions

* Removed changing different aspect ratios of displayed video.
+
Videos now always fill available space, while preserving their native aspect
ratio.

* Removed opening arbitrary videos in video player via `ctrl+m`.

=== Other changes

* Simplified videos opening.
+
Only videos linked to subtitles are played. Currently played video is changed
whenever a tab to subtitles with different video linked is opened. Playback is
also changed when a new video is linked.

* Property File Editor has more sane defaults pre-selected.

* Auto playback respects the current state of play button.

* Moved documentation from online wiki to `docs` directory.
+
If dependencies for generating a man page are met, it is automatically generated
when creating a binary package. This man page will be later installed with
Subconvert.

* Switch to py.test for running tests.

// vim: set tw=80 colorcolumn=81 :
