from ...tl.tlobject import TLObject


class PhoneCallDiscardReasonMissed(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    phoneCallDiscardReasonMissed#85e42301 = PhoneCallDiscardReason"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x85e42301
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xd89bad3d

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(PhoneCallDiscardReasonMissed.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return PhoneCallDiscardReasonMissed()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'phoneCallDiscardReasonMissed#85e42301 = PhoneCallDiscardReason'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
