# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170517_1145'),
        ('financial', '0002_auto_20170425_0010'),
        ('private_events', '0001_initial'),
        ('private_lessons', '0003_auto_20170518_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatelessonevent',
            name='danceType',
        ),
        migrations.RemoveField(
            model_name='privatelessonevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='privatelessonevent',
            name='role',
        ),
        migrations.AddField(
            model_name='instructoravailabilityslot',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructoravailabilityslot',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('T', 'Tentative Booking'), ('U', 'Unavailable')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='instructoravailabilityslot',
            name='tentativeExpirationDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 18, 18, 49, 17, 414900)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrivateLessonEvent',
        ),
        migrations.CreateModel(
            name='PrivateLessonEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.event',),
        ),
        migrations.AddField(
            model_name='instructoravailabilityslot',
            name='lessonEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='private_lessons.PrivateLessonEvent', verbose_name='Scheduled lesson'),
        ),
    ]
