
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-28T11:15:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "62684d6227bbb50b06c053e93b72dc027e3f4fec",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
