
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-13T20:25:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "913055cbfb3034f2e7495f8bd1ed1f41c614f072",
 "version": "0.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
