
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "12203335375f0e09e74d81f29b41c7f4b02b3742",
 "version": "0.post.dev493"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
