
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-30T16:41:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ad2e571fc34fac6c24e876f5366a7942f2c10a6",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
