# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_auto_20170821_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ('order', 'name'), 'permissions': (('view_environment', 'Can view environment'),), 'verbose_name': 'environment', 'verbose_name_plural': 'environments'},
        ),
    ]
