heat_template_version: pike

description: >
  OpenStack containerized Nova Placement API service

parameters:
  DockerNovaPlacementImage:
    description: image
    type: string
  DockerNovaPlacementConfigImage:
    description: The container image to use for the nova_placement config_volume
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  NovaPlacementBase:
    type: ../../puppet/services/nova-placement.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Nova Placement API role.
    value:
      service_name: {get_attr: [NovaPlacementBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [NovaPlacementBase, role_data, config_settings]
          - apache::default_vhost: false
      step_config: &step_config
        get_attr: [NovaPlacementBase, role_data, step_config]
      service_config_settings: {get_attr: [NovaPlacementBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: nova_placement
        puppet_tags: nova_config
        step_config: *step_config
        config_image: {get_param: DockerNovaPlacementConfigImage}
      kolla_config:
        /var/lib/kolla/config_files/nova_placement.json:
          command: /usr/sbin/httpd -DFOREGROUND
          config_files:
            - source: "/var/lib/kolla/config_files/src/*"
              dest: "/"
              merge: true
              preserve_properties: true
          permissions:
            - path: /var/log/nova
              owner: nova:nova
              recurse: true
      docker_config:
        # start this early so it is up before computes start reporting
        step_3:
          nova_placement:
            start_order: 1
            image: {get_param: DockerNovaPlacementImage}
            net: host
            user: root
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/nova_placement.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/puppet-generated/nova_placement/:/var/lib/kolla/config_files/src:ro
                  - /var/log/containers/nova:/var/log/nova
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create persistent logs directory
          file:
            path: /var/log/containers/nova
            state: directory
      upgrade_tasks:
        - name: Stop and disable nova_placement service (running under httpd)
          tags: step2
          service: name=httpd state=stopped enabled=no
