language: python
python:
  - "3.6"
install:
  - "pip install flit"
  - "pip install pytest-flask"
  - "pip install flake8"
  - "flit install --symlink"
script:
  - "flake8 flask_simplelogin/"
  - "flake8 example/"
  - "flake8 tests/"
  - "py.test -v tests/"
