from ...tl.tlobject import TLObject


class InputDocumentEmpty(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputDocumentEmpty#72f0eaae = InputDocument"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x72f0eaae
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xf33fdb68

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputDocumentEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputDocumentEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputDocumentEmpty#72f0eaae = InputDocument'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
