from ...tl.tlobject import TLObject


class InputPrivacyValueDisallowContacts(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputPrivacyValueDisallowContacts#0ba52007 = InputPrivacyRule"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xba52007
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x5a3b6b22

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputPrivacyValueDisallowContacts.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputPrivacyValueDisallowContacts()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPrivacyValueDisallowContacts#0ba52007 = InputPrivacyRule'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
