
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5ad37a3becc45eab59026c9a819276cf170729dc",
 "version": "0.1.post13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
