
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "817b04d68d7929cb8fccd7c44825b19bd7c33f35",
 "version": "0.9.post31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
