
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-09T15:24:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f33cf257fa28e7b89abaff9bed6bc4c6f645ac69",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
