
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1abd45e711801b936129c8f7d0778a7423a77f55",
 "version": "0.7.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
