language: python
python:
  - '2.7'
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: rjosephwright
    password:
      secure: MvRGz6OoUx3fN7HTqizUoVquvZNjNXLSulANkA5E+wz2JgTeEOk2vm97VpRF8UYE4ZbdHv10SEmxQ7jKYyzJBAMGAoiJVNQogsm7juaF+36hcQR5W+4b4QjP98h/z7jL1pcUOnFaDz1bLKkSnGsH94SyxC9i5KzBk09V2pa4SL5yRxQffYVPh0aH44TpNmDu4kCrxKVS5qDWpEvKJGLeC6oX7mDKAcXXmQ3XAL7ozJBCVooDlUnMhQmU0iIaoC7NqHICzg/Ct62CBwAcHGozbk9iVr7aiTpd0ZPHRw7GHMsSqSUirOVUe7ycS5ejTdyNVddg1xTJm/U9CiltbvXhA7eKDXwjlmt9rNCutWfpi85j7LNp96v35bAGUkhRf+KjRA7nFLIcj85pFtBKQ0C2sj6vMT9PR8fx8R+RpWdjSzP3NKfSk7qtZXKQRX6TDmzZUz7sYJxdyEvQpPdNJxv9tCIYRqYO0SB8ILE4GEw0ahU16NH4miQ9qftd5rE3H3oM4EwR/w/7c+hkPeZe7qM3znaDs+YO3qWr7ufGf2W/kZ8byr/uE3Bd9ucjEmaXeHzWPkUqkM3Nxxi+rSDpfvAZ/XB3wgekV3yte6JaMNdC+q6PsRDG8Vf3zoT4+5l7gLljScnkzSCqzloSlDhyaI+G1fNenKoyvXc89/+plS6rvFU=
    on:
      tags: true
    distributions: sdist bdist_wheel
    repo: cloudboss/friend
