version: '{build}'
platform: x64
configuration: Release
os: Visual Studio 2015

install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - set MSYSTEM=MINGW64
    - bash -lc ""
    - bash -lc "pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel"
    # kludge for error: "mingw-w64-x86_64-gcc: /mingw64/etc/gdbinit exists in filesystem"
    - bash -lc "rm -f /mingw64/etc/gdbinit"
    # we don't actually need ada, fortran, libgfortran, or objc, but in
    # order to update gcc we need to also update those packages as well...
    - bash -lc "pacman --noconfirm --needed -S mingw-w64-x86_64-{gcc,gcc-ada,gcc-fortran,gcc-libgfortran,gcc-objc,cmake,make,icu,jemalloc,zlib}"
before_build:
    - set MSYSTEM=MINGW64
    - cd C:\projects\meta
    - git submodule update --init --recursive
    - bash -lc "export PATH=/mingw64/bin:$PATH && cd $APPVEYOR_BUILD_FOLDER && mkdir build && cd build && cmake .. -G \"MSYS Makefiles\""
build_script:
    - set MSYSTEM=MINGW64
    - bash -lc "export PATH=/mingw64/bin:$PATH && cd $APPVEYOR_BUILD_FOLDER/build && make -j2"
test_script:
    - set MSYSTEM=MINGW64
    - bash -lc "export PATH=/mingw64/bin:$PATH && cd $APPVEYOR_BUILD_FOLDER/build && cp ../config.toml . && ./unit-test --reporter=spec"
