language: python
python:
- 2.7
- 3.6
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=flake8
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: b.4hand
  password:
    secure: sZ79NteXgf11r1rllu/sKlpgxFQMa0QnNEmnGBkKlMbjhXRUE2by5mUU2/yEswZ+s+YuNr0v6In3Gu71i9wCXCVFsbJn6P4/k/AcjJ+SNUudFqPvynF/WpmMbbw5ZFkpc1p+fF1QW3iYyInGGxZRomlXSBAGwKUbUtzU6UD41q+pGYR2CFJnKJCn9NQ+MOCLu6bgL6JgVeBdA7OP3aiIvmDkF/Eed4SPNFOWGjkMWAtvlVrm/eUfAqfqx1iXEI5CAVHhNyHj+jkK6U493Pka5jhTMig/OkIrVtqhAtnPJb8YL4fa05XnOQRIkdt1QLhhjx8gekei0XFL65CWVmDPFGrWy5B1pjtx/4f1hgBtp8NzgDSFDpcN8WjkBsqC6hAfwadlm+CbiNtmY9Gusz5+pV6A+PPy3x9P1Q5EIPmKO1z0xNqTmgEyvHrvIoqOB+DBYRTUfqHOOwM3p2ZbJgFBQWEou9s55HVsoZJKVqYBuPJQOrHFkL+PDdJqI6hYWh1ZbEpVV4ZMPu9v/M2gPABF8gWl1nsKQhniHbw3x9SAUeWk+2TLzV1GetMdJd+AbfdWBlAINp2K9Yui03t3KvXrrj0TXhV+S8BRpeTEufcJBVWt9NuPqkhUrzwBrtdZ+ePeE7+VWFfS4RDtPrWyibjQmzCApU6/0VyiWWL0S7JVBqM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: jrbenny35/pytest-firefox
