# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(blank=True),
        ),

    ]
