# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '1.0.0'
VERSION = '1.0.0'
FULL_VERSION = '1.0.0'
GIT_REVISION = '195a62d2f7d153d3c79e15d0d8c0e6b67bbd2d18'
GIT_VERSION = '1.0.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
