
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d64f5275ef6acc2072e123315700b320d179dc13",
 "version": "0.2.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
