/* Generated by Cython 0.26 */

#ifndef __PYX_HAVE__recfast4py___recfast
#define __PYX_HAVE__recfast4py___recfast


#ifndef __PYX_HAVE_API__recfast4py___recfast

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C std::string installPath;

#endif /* !__PYX_HAVE_API__recfast4py___recfast */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_recfast(void);
#else
PyMODINIT_FUNC PyInit__recfast(void);
#endif

#endif /* !__PYX_HAVE__recfast4py___recfast */
