# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
language: python
matrix:
  include:
  - env: CACHE_NAME=latest SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/ SAGE_AGE=0
  - env: CACHE_NAME=older SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/ SAGE_AGE=1
  allow_failures:
  - env: CACHE_NAME=older SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/ SAGE_AGE=1
install: ./.travis-install.sh
script: ./.travis-test.sh
cache:
  directories:
  - $HOME/sagemath
  - $HOME/.cache/matplotlib
  timeout: 1000
before_cache:
- rm -rf $HOME/sagemath/logs $HOME/sagemath/.BUILDSTART
#after_success:
#- ./.travis-deploy-doc.sh
#before_script:
#- openssl aes-256-cbc -K $encrypted_f96cc3b3888c_key -iv $encrypted_f96cc3b3888c_iv
#  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d || true
