
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-13T11:16:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3b5a04fa76e15a2113a5dde470c8cd665938abe",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
