# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0002_auto_20160219_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Use only base environment'),
        ),
        migrations.AlterField(
            model_name='component',
            name='require_schema',
            field=models.BooleanField(default=True, help_text='Use json schema validation'),
        ),
    ]
