# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0007_auto_20170725_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='schema_json',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
