# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0009_auto_20170726_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='schema',
        ),
    ]
