sudo: false
language: python
cache: pip

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy3.3-5.2-alpha1

env:
  matrix:
    - TOXENV=py
  global:
    secure: IFQzIw/g6qbmZy86w9qPU5vZjoJWtBlP8VpUtBX+La9hyZ6odC0pxB38U7IQNnPKinUvnc0cGEsAJS/abxp3bSdS0H+afr8OjxOgDuLBl47fMHBxFUMF6HRFmKuk66GfM1sxf87xLdiPDF5Dac0cn7IlJrFkQaCukZjinvZRvtU=

matrix:
  allow_failures:
    - python: 3.7-dev
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=docs
    - os: osx
      language: generic
      env: TOXENV=py
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - # Run tests with optional dependencies:
      python: 3.6
      after_install:
        - echo click_repl >> requirements.txt

addons:
  apt:
    packages:
      - language-pack-de

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - codecov

before_deploy:
  - pip install wheel
  - python setup.py sdist bdist_wheel

deploy:
  - provider: pypi
    user: hobarrera
    password:
      secure: LXSgJZMZICS0Xv5qyR/IRgki1Wy23lurmdepsOsjzBM2fv7rgKPlU/MASVCUCmLi9vYYqZu+7ViHeT6uhJXLdwE0NisVYqTg6L4aD1kqDmbjkWFhLKA7DAz1QTAYxrk6TQYmDb+ZbNFZlF21g29nqvqtLwdC4dFnDjXGnupCoeU=
    on:
      tags: true
    distributions: "sdist bdist_wheel"
  - provider: releases
    api_key:
      secure: g60yeYa+BX7XCe7L4mpV5NiaCPkuJzxk+PP3rL/durPF/CudWW2xUuTCLf30WwfrYBg3bJCQKNnzOpL8+d4Maly3UqquDFjK58Z/JBFw6erzg/RAxAnfJzFbWy2mgqKTpBHaDdRnhVtqp23Ov1I/+Jb51DIhij6ILNgGxW1OP8Y=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
    distributions: "sdist bdist_wheel"
