from ...tl.tlobject import TLObject


class PeerNotifySettingsEmpty(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    peerNotifySettingsEmpty#70a68512 = PeerNotifySettings"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x70a68512
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xcf20c074

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(PeerNotifySettingsEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return PeerNotifySettingsEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'peerNotifySettingsEmpty#70a68512 = PeerNotifySettings'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
