
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-31T07:33:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea4186bac5c537298aebcc45e513e14be8efc597",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
