
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-03T21:35:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d58fc4da1faca943211d8d07e76f76e32e8c450d",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
