# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HostingAccountTokens(Model):
    """Access keys for the hosting account calls.

    :param access_token: The access token to Model Management Service.
    :type access_token: str
    """

    _attribute_map = {
        'access_token': {'key': 'accessToken', 'type': 'str'},
    }

    def __init__(self, access_token=None):
        self.access_token = access_token
