
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-25T23:32:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8f53c3938e6b3538feaa4733977ab5aea78d3db",
 "version": "2.11.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
