sudo: false
language: python
python:
  - "nightly"
  - "3.7-dev"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"

install:
- pip install -r test-requirements.txt

script:
  - export PYTHONPATH=`python -c "import sys; print('python2' if sys.version.startswith('2') else 'src')"`; py.test $PYTHONPATH
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 --config=.flake8-tests src/test_typing.py python2/test_typing.py; fi
