# Use this file to store sensitive settings
# put it in your .gitignore and do not push to the repo
# or even better: ALWAYS USE ENVIRONMENT VARIABLES for sensitive data
# export QUOKKA_SECRET_KEY=1234
# and dynaconf will take it from there

quokka:
  SECRET_KEY: abcderf
