from ...tl.tlobject import TLObject


class InputNotifyAll(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputNotifyAll#a429b886 = InputNotifyPeer"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xa429b886
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x58981615

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputNotifyAll.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputNotifyAll()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputNotifyAll#a429b886 = InputNotifyPeer'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
