from ...tl.tlobject import TLObject


class WebPageEmpty(TLObject):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    webPageEmpty#eb1477e8 id:long = WebPage"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xeb1477e8
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x55a97481

    def __init__(self, id):
        """
        :param id: Telegram type: "long".

        Constructor for WebPage: Instance of either WebPageEmpty, WebPagePending, WebPage, WebPageNotModified.
        """
        super().__init__()

        self.id = id

    def to_dict(self):
        return {
            'id': self.id,
        }

    def on_send(self, writer):
        writer.write_int(WebPageEmpty.constructor_id, signed=False)
        writer.write_long(self.id)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return WebPageEmpty(None)

    def on_response(self, reader):
        self.id = reader.read_long()

    def __repr__(self):
        return 'webPageEmpty#eb1477e8 id:long = WebPage'

    def __str__(self):
        return TLObject.pretty_format(self)

    def stringify(self):
        return TLObject.pretty_format(self, indent=0)
