language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install codecov

script: python -m pytest --verbose --cov=myr/base --cov-report=term-missing tests

after_success:
    - codecov
