
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-23T10:09:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d2dc9be0afef740a9702e10422e5f516a7446fd",
 "version": "2.11.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
