
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-10T17:59:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "63db0a513a0a5237d90f30d81c660af9d044af85",
 "version": "v1.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
